nix-community/stylix

- flake.nix
- modules/mako.nix
> Initial mako config

- README.md
- default.nix
- flake.lock
- flake.nix
> Add explanations on how to install Stylix without flakes

- modules/kitty/hm.nix
Directly use upstream template and add an option to use the 256 colors variant.
> Improve kitty module

- FAQ.md
- TRICKS.md
- docs/default.nix
- flake.lock
> FAQ.md Added

- modules/avizo/hm.nix
- modules/waybar/hm.nix
some basic support for waybar and avizo
> add waybar and avizo support

- modules/waybar/base.css
- modules/waybar/center.css
- modules/waybar/hm.nix
- modules/waybar/left.css
- modules/waybar/right.css
fixes this pull request covers so far
1. creates the options enableRightBackColors, enableCenterBackColors, and enableLeftBackColors, that are set to false by default.
2. sets the font color to base00.
3. adds some modules i missed.
4. seperated some theming stuff into seperate css files.
> fix waybar modules

- stylix/palette.nix
Fix in #79  is missing this bit
> Fix palette generation when system does not use stylix

- modules/zellij/hm.nix
Adds a Zellij support. Closes #107
> Implemented Zellij Support

- modules/avizo/hm.nix
> Fix Avizo RGBA format

- docs/src/tricks.md
Add trick with dynamic wallpaper generation based on the selected theme to docs
> Add trick with dynamic wallpaper generation

- modules/gtk/hm.nix
fixed extraCss being at the beginning of the css file, now at the end
> fix(modules/gtk/hm.nix): fixed extraCss

- modules/emacs/hm.nix
see https://github.com/nix-community/home-manager/commit/19c6a4081b14443420358262f8416149bd79561a
> epkgs.trivialBuild: set dummy version

- flake.lock
- modules/hyprland/hm.nix
as of now, this only adds window borders, ill work on group borders later
> add basic hyprland support

- modules/bat/hm.nix
Blocked on: https://github.com/nix-community/home-manager/pull/4539
> fix(bat): don't use IFD

- modules/kitty/hm.nix
https://github.com/danth/stylix/issues/159
> fix(kitty): don't use IFD

- flake.lock
- flake.nix
- modules/xresources/hm.nix
- stylix/templates.nix
https://github.com/danth/stylix/issues/159
> fix(modules/xresources): embed template to avoid IFD

- modules/xfce/hm.nix
As of now, it just adds font support for Xfce4. I'll work on wallpaper support later :)
> Add font support for Xfce4

- modules/kmscon/nixos.nix
> kmscon: set font face

- modules/firefox/hm.nix
This changes Firefox fonts based on Stylix configuration.
> Add Firefox module

- flake.lock
- modules/bemenu/hm.nix
HM just added a new bemenu module upstream, so this commit changes the stylix bemenu module to use that instead.
> bemenu: Move over to HM's module

- flake.lock
- flake.nix
- modules/gnome/theme.nix
- modules/plymouth/nixos.nix
- stylix/templates.nix
Closes: https://github.com/danth/stylix/issues/222
Additionally, I took the luxury to sort the `inputs` in `flake.nix`.
> perf(flake): remove runtime fetch operations

- modules/qutebrowser/hm.nix
This PR should be merged after https://github.com/danth/stylix/pull/239.
> qutebrowser: improve readability

- modules/lazygit/hm.nix
Thanks for creating this module, it's really useful!
Thought I'd give back by adding a module for lazygit
> lazygit: add module for lazygit

- docs/src/styling.md
Closes #277. See the issue for more details.
> doc: change selection background to `base02`

- .gitignore
Reference: 
- https://github.com/github/gitignore/pull/4398
> stylix: add gitignore file

- modules/mangohud/hm.nix
Related:
- https://github.com/danth/stylix/issues/251.
> mangohud: link to tracking issue

- modules/gnome/hm.nix
- modules/kde/hm.nix
Related: https://stackoverflow.com/questions/3427872
> treewide: use Bash internal 'test' command

- modules/kde/hm.nix
Apply Bash best practices to improve maintainability.
> kde: apply Bash best practices

- stylix/palette.nix
I made this change a long time ago in #50, but it never got merged.
> stylix: escape spaces in wallpaper path

- modules/kde/hm.nix
- Addresses:
- https://github.com/danth/stylix/issues/313#issuecomment-2028914352
- Follows:
- https://github.com/danth/stylix/pull/304
> kde: use provided 'verboseEcho' function

- modules/plymouth/nixos.nix
Addresses: https://github.com/NixOS/nixos-artwork/pull/120
Closes: https://github.com/danth/stylix/issues/334
> plymouth: lock URL version

- modules/bemenu/hm.nix
- modules/gnome/nixos.nix
- modules/grub/nixos.nix
- modules/gtk/hm.nix
- modules/kitty/hm.nix
- modules/plymouth/nixos.nix
- modules/swaylock/hm.nix
- modules/waybar/hm.nix
- stylix/cursor.nix
- stylix/darwin/default.nix
- stylix/fonts.nix
- stylix/nixos/default.nix
- stylix/opacity.nix
- stylix/palette.nix
- stylix/target.nix
> treewide: remove `lib.mdDoc`

- modules/gitui/hm.nix
Based myself off this example: https://github.com/catppuccin/gitui/blob/main/theme/mocha.ron
> gitui: init

- modules/plymouth/nixos.nix
Backport of #335 and #338
Closes #356
> plymouth: backport URL locking

- stylix/testbed.nix
This allows restarting services and accessing protected files during testing.
> stylix: provide root access in testbeds

- modules/vesktop/hm.nix
- modules/vesktop/template.mustache
Adds a generated theme to Vesktop. (might need extra tweaks for the colors)
Closes #364
> vesktop: init

- README.md
This screenshot was taken in Plasma 5, not Plasma 6.
> doc: Plasma 6 → Plasma 5

- modules/wpaperd/hm.nix
Add stylix target for [wpaperd](https://github.com/danyspin97/wpaperd)
> wpaperd: init

- modules/tofi/hm.nix
change the tofi implementation to also use opacity in its hex colors
> tofi: use opacity

- modules/vim/hm.nix
This seems a stray cat from PR https://github.com/danth/stylix/pull/425
> vim: fix missing lib prefix (#432)

- modules/plymouth/nixos.nix
> plymouth: use logo from `nixos-icons`

- flake.lock
> lock: updating helix-base16 input

- modules/neovim/hm.nix
- modules/vim/hm.nix
> neovim: init

- modules/nixvim/nixvim.nix
See https://github.com/danth/stylix/pull/496#discussion_r1704353280
> nixvim: rename transparency options to camelCase

- .github/workflows/docs.yml
This combines #522 and #523 into a single commit, since the actions require to be updated together (see their changelog for details).
> ci: update Actions related to GitHub Pages

- modules/hyprlock/hm.nix
> hyprlock: init

- flake.lock
Closes: https://github.com/danth/stylix/issues/625
> stylix: bump base16 input

- flake.lock
> Fix base16 input

- flake.lock
- modules/tmux/hm.nix
This fixes build failures in the tmux module as well
> chore: update flake inputs

- modules/river/hm.nix
[River](https://codeberg.org/river/river) is a dynamic tiling Wayland compositor with flexible runtime configuration.
New module to set the colors and cursor.
> river: init new module

- flake.lock
- flake.nix
- modules/gnome/colors.mustache
Closes: https://github.com/danth/stylix/issues/618
> gnome: update to GNOME 47.2

- LICENSE
Link: https://github.com/NixOS/nixpkgs/pull/11557
Link: https://github.com/danth/stylix/pull/659
> doc: update copyright and include contributors

- docs/src/modules.md
This PR follows the following discussion:
> > Should we require new modules to provide a testbed once this PR merges, or is it still too early considering the overall state of https://github.com/danth/stylix/issues/319?
>
> [...]
>
> It could be something we recommend in [this guide](https://stylix.danth.me/modules.html) for example.
>
> -- https://github.com/danth/stylix/pull/612#issuecomment-2532155680
> doc: encourage adding testbeds for new modules

- modules/firefox/hm.nix
- modules/librewolf/hm.nix
A copy of the Firefox module, don't think there's a better way to do it. Would be great if this could be backported to 24.11.
> librewolf: init

- modules/micro/hm.nix
Cc: @matkijahenkilo
---
Closes: https://github.com/danth/stylix/issues/714
> micro: init

- .github/workflows/backport.yml
```console
git cherry-pick -x b08769f64e6f 5a69e8c65787
```
> [release-24.11] cherry-pick b08769f64e6f and 5a69e8c65787

- modules/alacritty/testbed.nix
- modules/emacs/testbed.nix
- modules/firefox/testbed.nix
- modules/foot/testbed.nix
- modules/hyprland/testbed.nix
- modules/kitty/testbed.nix
- modules/qutebrowser/testbed.nix
- modules/vscode/testbed.nix
- modules/wezterm/testbed.nix
- modules/zathura/testbed.nix
> [release-24.11] treewide: use lib.singleton

- modules/glance/hm.nix
- modules/glance/testbed.nix
Glance is a self-hosted dashboard that puts all your feeds in one place.
The testbed is kind of a hack but does work.
> glance: init

- modules/qt/hm.nix
```
Fixes: b7f50a56c3cc ("qt: add flexible theming with sensible defaults (#780)")
```
Cc: @Mikilio
> qt: respect stylix.enable

- flake.lock
> firefox: update GNOME theme input

- flake.lock
- modules/vscode/hm.nix
- modules/wpaperd/hm.nix
Resolve #903 
Note:
VSCode have now profile settings with this setup it will apply stylix to only default profile.
> Rename options for programs.wpaperd and programs.vscode

- stylix/testbed.nix
```
Fixes: f121a142abde ("stylix: parametrize and change testbed field separator (#887)")
```
> stylix: apply testbed field separator check to each fields

- stylix/fonts.nix
> stylix: use new package name for Noto Color Emoji

- modules/hyprlock/hm.nix
> Convert image path to string for Hyprlock fixing #918

- modules/vscode/hm.nix
> vscode: support arbitrary profiles

- modules/fnott/hm.nix
> fnott: init

- docs/settings.nix
```
Fixes: c8e4a0d2186d ("treewide: optionalize stylix.image option (#717)")
```
> stylix: simplify dummy values

- modules/dunst/hm.nix
https://github.com/danth/stylix/pull/948#discussion_r1980128732
cc: @trueNAHO
> dunst: fix opacity rounding

- stylix/darwin/default.nix
Fixes the issue introduced in #924
> stylix: system.darwin.release -> system.darwinRelease

- modules/starship/hm.nix
- modules/starship/meta.nix
- modules/starship/testbed.nix
- stylix/maintainers.nix
Closes: https://github.com/danth/stylix/issues/301
> starship: init

- modules/chromium/meta.nix
- modules/eog/meta.nix
- modules/firefox/meta.nix
- modules/gnome/meta.nix
- modules/gtk/meta.nix
- modules/plymouth/meta.nix
- modules/vscode/meta.nix
Added myself to the targets I'm most familiar with. Most of these are programs I currently have installed, so I will notice if their modules need updating.
If some modules are left unmaintained after we've pinged other contributors, I'll look at adding myself to those which I originally authored but no longer use.
> treewide: add danth as maintainer

- flake.lock
- modules/fnott/meta.nix
- modules/mpv/meta.nix
- modules/ncspot/meta.nix
- modules/waybar/meta.nix
had to update nixpkgs b/c I was recently [added as a nixpkgs maintainer](https://github.com/NixOS/nixpkgs/pull/375653/)
> treewide: add awwpotato as maintainer

- modules/avizo/hm.nix
> avizo: hotfix aviOpcaity missing

- docs/default.nix
- stylix/meta.nix
As promised at https://github.com/danth/stylix/pull/977#pullrequestreview-2683388232
> doc: display module maintainers

- modules/lazygit/meta.nix
- modules/mako/meta.nix
- modules/sxiv/meta.nix
- modules/wofi/meta.nix
- modules/zathura/meta.nix
I'm not entirely sure if adding myself as co-maintainer is ok, but I did it anyway :sunglasses:. If it's not, I'll undo it.
> treewide: add mateusauler as maintainer

- .github/PULL_REQUEST_TEMPLATE.md
heavily inspired by [nixpkgs's pr template](https://github.com/NixOS/nixpkgs/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1) and [home manager's template](https://github.com/nix-community/home-manager/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1)
> doc: add GitHub PR template

- stylix/maintainers.nix
> stylix: remove empty line in maintainers list

- stylix/maintainers.nix
Fixes: e43eb4e2a7df ("stylix: init module maintainers framework (#977)")
> stylix: wrap code comment to 80 characters

- modules/mpv/hm.nix
- modules/mpv/testbeds/modernz.nix
> mpvScripts.modernz: init

- .github/PULL_REQUEST_TEMPLATE.md
Made this not nested under "Things done", and replaced "CC" with "Notify" for clarity.
> doc: improve maintainer subheading in PR template

- .github/PULL_REQUEST_TEMPLATE.md
This serves as a reminder to check licenses properly. It's intentionally vague to avoid giving wrong advice.
> doc: add license check to PR template

- .github/workflows/check.yml
- .github/workflows/docs.yml
Link: https://woodruffw.github.io/zizmor/audits/#artipacked
> ci: prevent unintentional credential persistence

- modules/bemenu/meta.nix
> bemenu: add noodlez1232 as maintainer

- modules/discord/hm.nix
related to #704, #481
@Flameopathic
> discord: add extraCss option

- docs/src/tricks.md
> docs: add trick abt lib.mkAfter

- stylix/home-manager-integration.nix
https://github.com/danth/stylix/issues/865#issuecomment-2767422654
> stylix: add missing parentheses around mkMerge

- modules/neovim/README.md
- modules/nixvim/README.md
- modules/nvf/README.md
- modules/vim/README.md
See https://github.com/danth/stylix/pull/1039#pullrequestreview-2707260155
> doc: add links between NVF, Neovim, Nixvim, and Vim pages

- docs/default.nix
Added the link I used in [this comment](https://github.com/danth/stylix/pull/1059#issuecomment-2772012443) to further explain `markdownInHTML`.
> doc: add link to CommonMark Spec

- .github/ISSUE_TEMPLATE/bug.yml
addresses https://github.com/danth/stylix/pull/921#issuecomment-2750719326
> doc: collapse flake.lock in GitHub bug template

- modules/discord/template.nix
Updating the CSS template for discord, as the new ui redesign broke it.
Resolves #1062
@Flameopathic
> discord: fix template for  new ui redesign

- modules/bat/testbeds/default.nix
- stylix/testbed.nix
changes:
- adds bat testbed
- prints example markdown file
- makes all testbeds automatically log into tty as guest
related: #319 
@trueNAHO
> bat: add testbed

- .github/workflows/update-flake.yml
See https://github.com/danth/stylix/pull/1100#discussion_r2029957053
> ci: remove `github_actions` label

- .github/workflows/update-flake.yml
currently is borked https://github.com/danth/stylix/pull/1101
> ci: adjust flake update PR and commit messages

- .github/workflows/update-flake.yml
as discussed in https://github.com/danth/stylix/pull/1100#issuecomment-2781084603
> ci: run flake update on stable release

- .github/workflows/check.yml
- docs/src/development_environment.md
- flake.nix
> [release-24.11] ci: run all builds in a single job

- modules/mpv/hm.nix
Resolves #1096
@trueNAHO 
CC @awwpotato
> mpv: unset OSD font size

- modules/hyprland/hm.nix
> [release-24.11] hyprland: disable default wallpaper when hyprpaper is enabled

- .github/workflows/backport.yml
currently the backport action is failing on 24.11 https://github.com/danth/stylix/actions/runs/14339764722/job/40195882553
> [release-24.11] ci: update github app secrets

- .github/workflows/backport.yml
> [release-24.11] ci: use correct name for private key secret

- .github/workflows/update-flake.yml
the pr title for stable flake update should be prefixed with `[release-foo.bar]`
> ci: include release branch in update PR title

- flake.nix
- modules/firefox/hm.nix
- stylix/testbed.nix
> stylix: disallow nixpkgs aliases in testbeds

- .github/workflows/backport.yml
- .github/workflows/update-flake.yml
Makes the perms granted more explicit. Based on pr to nixpkgs https://github.com/NixOS/nixpkgs/pull/398180.
> ci: explicit permissions for github app token

- modules/fcitx5/hm.nix
> fcitx5: enable theme, refactor

- modules/gitui/hm.nix
> gitui: switch from rgb to hex

- docs/src/testbeds.md
doesn't make much since to recommend one thing in the docs then tell people to change it in their pr
> docs: use lib.singleton

- modules/gtk/hm.nix
> gtk: assert hm extraCss option is unset

- docs/default.nix
> doc: display GitHub handles in maintainer sections

- modules/gtk/hm.nix
> gtk: invert extraCss warning

- .github/workflows/update-flake.yml
so turns out it's reversed. Also switched to start with.
> ci: fix update flake pr title condition

- modules/gitui/hm.nix
Hi folks :)
The two curly braces probably got left over from the recent refactor (#1144 and #1154). Unfortunately i didn't recognize them when i had a look at those patches.
When i tested a recent version of stylix (rev: f46d58be39a7822a88f29b1650ec14c961c81414), stylix generated this `theme.ron`:
```ron
(
selected_tab: Some("Reset"),
command_fg: Some("#d5c4a1"),
selection_bg: Some("#bdae93"),
selection_fg: Some("#d5c4a1"),
cmdbar_bg: Some("#3c3836"),
cmdbar_extra_lines_bg: Some("#3c3836"),
disabled_fg: Some("#bdae93"),
diff_line_add: Some("#b8bb26"),
diff_line_delete: Some("#fb4934"),
diff_file_added: Some("#fabd2f"),
diff_file_removed: Some("#fb4934"),
diff_file_moved: Some("#d3869b"),
diff_file_modified: Some("#fe8019"),
commit_hash: Some("#fbf1c7"),
commit_time: Some("#d5c4a1"}), …
```
> gitui: fix two typos

- flake.lock
- flake.nix
my pr got merged https://github.com/SenchoPens/base16.nix/pull/24
> stylix: switch back to original base16.nix

- modules/spotify-player/hm.nix
- modules/spotify-player/meta.nix
- stylix/maintainers.nix
Added target spotify-player. used string interpolation, saw that mustache thing but don't properly understand how to use that haha. feel free to correct anything
> spotify-player: init

- .github/workflows/backport.yml
- .github/workflows/check.yml
- .github/workflows/docs.yml
to prevent #1149 from generating a ton of merge conflicts
> [release-24.11] ci: sync with master

- modules/btop/testbeds/default.nix
changes:
- adds btop testbed
- runs btop in terminal emulator
related: #319 
@trueNAHO
> btop: add testbed

- .github/workflows/update-flake.yml
> ci: fix stable pr title for update flake

- flake.lock
- modules/foot/hm.nix
> [release-24.11] stylix: update base16.nix

- modules/eog/testbeds/default.nix
> eog: add testbed

- modules/lazygit/testbeds/default.nix
> lazygit: add testbed

- flake.lock
- flake.nix
- modules/mako/hm.nix
> mako: update to new home-manager module

- stylix/overlays.nix
> stylix: set _file for overlays

- flake.lock
- flake.nix
- modules/mako/hm.nix
https://github.com/nix-community/home-manager/pull/6968
> mako: remove typo from hm module

- stylix/darwin/default.nix
- stylix/droid/default.nix
- stylix/droid/palette.nix
- stylix/hm/default.nix
- stylix/nixos/default.nix
https://noogle.dev/f/lib/modules/importApply
> stylix: use lib.modules.importApply

- modules/qutebrowser/hm.nix
> qutebrowser: do not enable darkmode

- modules/fzf/testbeds/default.nix
Does not work in its current state. fzf is opened as expected, but nothing is themed.
Related: #319 
@trueNAHO
> fzf: add testbed

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/change_option.yml
- .github/ISSUE_TEMPLATE/change_target.yml
- .github/ISSUE_TEMPLATE/new_option.yml
- .github/ISSUE_TEMPLATE/new_target.yml
> doc: direct to all issues instead of open ones in issue templates

- docs/src/tricks.md
- modules/feh/hm.nix
- modules/feh/nixos.nix
- modules/grub/nixos.nix
- modules/kde/hm.nix
- modules/plymouth/nixos.nix
- modules/regreet/nixos.nix
- palette-generator/default.nix
- stylix/palette.nix
- stylix/pixel.nix
> treewide: use lib.getExe

- .github/labeler.yml
- .github/workflows/labels.yml
> ci: add labeler action

- stylix/maintainers.nix
> stylix: emphasize compliance with Nixpkgs maintainer list

- modules/yazi/hm.nix
- Removes the explicit foreground color for `hovered`, so that the original color in the selected item is retained.
- Themes the copied, cut and selected counter in the top right
> yazi: more color tweaks

- modules/wayprompt/hm.nix
- modules/wayprompt/meta.nix
Ah, affter adding the Home Manager module last week (nix-community/home-manager#7009), I was on my way to add support [here](https://github.com/panchoh/stylix/commit/46bec69ca637b003c9197d90b532c40caa7acadd), but you [beat me](https://github.com/danth/stylix/pull/1250) to it! :wink:
I’ve tweaked the module a bit, hope that you like the changes.
I’ve also added myself as a maintainer.
Cheers!
@nukdokplex @awwpotato
> Wayprompt tweaks

- docs/src/development_environment.md
- docs/src/installation.md
- docs/src/modules.md
- docs/src/options/platforms/home_manager.md
- docs/src/styling.md
- docs/src/testbeds.md
- docs/src/tricks.md
> doc: wrap to width of 80

- modules/discord/hm.nix
> nixcord: change theme location on nix-darwin

- flake.lock
- modules/mako/hm.nix
Because it is depracated:
https://github.com/nix-community/home-manager/commit/0be2c246e37a5b6e851111bfcf07ab37194e4954
@mateusauler
> mako: don't use criteria option

- .github/workflows/update-flake.yml
- docs/src/commit_convention.md
- flake.lock
- flake.nix
- flake/default.nix
- flake/dev-shell.nix
- flake/modules.nix
- flake/packages.nix
- flake/pre-commit.nix
Related: #927 
CC: @MattSturgeon
> flake: use flake-parts

- flake/modules.nix
- flake/packages.nix
> flake: use importApply for modules

- docs/default.nix
- flake/packages.nix
https://github.com/danth/stylix/pull/1281#discussion_r2093634998
cc @MattSturgeon @trueNAHO 
built locally to confirm it's working
> doc: use callPackage

- .github/dependabot.yml
https://github.com/danth/stylix/pull/1286#issuecomment-2887742066
> ci: fix dependabot backport label

- docs/src/development_environment.md
Added a subsection on the 'Development Environment' section that explains how to build and check the changes to the documentation *locally*.
I had to look for it on the GitHub workflows, so I thought it would be a good idea to have it properly documented.
> doc: explain how to build & check the docs locally

- stylix/palette.html.mustache
Noticed this while doing a find-and-replace for #1297.
> stylix: update documentation URL in palette.html

- .github/workflows/backport.yml
- README.md
- docs/book.toml
- docs/src/installation.md
- docs/src/modules.md
- docs/src/testbeds.md
- flake.nix
- modules/kde/hm.nix
- modules/mangohud/hm.nix
- modules/micro/hm.nix
- modules/qutebrowser/hm.nix
- modules/xfce/hm.nix
> [release-24.11] treewide: change repository owner to nix-community

- README.md
- docs/src/installation.md
> doc: update nix-darwin owner

- docs/src/installation.md
Manual backport of https://github.com/nix-community/stylix/pull/1301
> [release-24.11] doc: update nix-darwin owner

- modules/gnome/hm.nix
> [release-24.11] gnome: install User Themes extension

- docs/src/modules.md
> doc: danth/stylix -> nix-community/stylix

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/change_option.yml
- .github/ISSUE_TEMPLATE/change_target.yml
- .github/ISSUE_TEMPLATE/new_option.yml
- .github/PULL_REQUEST_TEMPLATE.md
- docs/src/development_environment.md
- stylix/palette.html.mustache
Follow-up to c8f09c164b6490613ccee5a083f22095385bef5c
> treewide: update documentation links

- doc/default.nix
- stylix/home-manager-integration.nix
- stylix/testbed.nix
> treewide: remove unnecessary builtins prefix

- flake/packages.nix
- modules/discord/testbeds/vencord.nix
- stylix/testbed.nix
https://github.com/nix-community/stylix/pull/1291#issuecomment-2897168014
> stylix: improve how discord testbed is disabled

- .github/workflows/conflicts.yml
> ci: fix tag for label merge conflicts

- .github/workflows/conflicts.yml
https://github.com/nix-community/stylix/pull/1269#issuecomment-2899368742
> ci: used maintained conflicts action

- modules/gnome/hm.nix
https://github.com/nix-community/stylix/pull/1306#issuecomment-2894848902
related to https://github.com/nix-community/stylix/pull/1244
cc @alyraffauf @MattSturgeon 
@danth
> gnome: don't apply hm on darwin

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/change_option.yml
- .github/ISSUE_TEMPLATE/change_target.yml
- .github/ISSUE_TEMPLATE/new_option.yml
- .github/ISSUE_TEMPLATE/new_target.yml
- .github/labeler.yml
- .github/workflows/backport.yml
- .github/workflows/update-flake.yml
as discussed in https://github.com/danth/stylix/discussions/1109#discussioncomment-13110835
> [!WARNING]
> The labels also need to be renamed when merged this pr
> stylix: prefix labels with type

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/change_option.yml
- .github/ISSUE_TEMPLATE/change_target.yml
- .github/ISSUE_TEMPLATE/new_option.yml
- .github/ISSUE_TEMPLATE/new_target.yml
- .github/labeler.yml
- .github/workflows/backport.yml
- .github/workflows/update-flake.yml
backport of https://github.com/nix-community/stylix/pull/1256
> [release-25.05] ci: prefix labels with type

- modules/hyprlock/hm.nix
- modules/hyprlock/meta.nix
- **hyprlock: add MrSom3body as maintainer**
- **hyprlock: fix setting background**
See commits
> hyprlock: fix setting background

- modules/tofi/hm.nix
```
Fixes: 7ffb31da6985 ("treewide: use mkTarget (batch 2) (#1362)")
```
> tofi: add missing lib module argument

- stylix/overlays.nix
required for https://github.com/nix-community/stylix/pull/1371
> stylix: allow for overlays to access options

- doc/src/installation.md
Shouldn't be merged until nixpkgs 25.05 release on 2025-05-23 (https://github.com/NixOS/nixpkgs/issues/390768)
> doc: recommend 25.05 as stable version

- doc/src/testbeds.md
Followup to https://github.com/nix-community/stylix/pull/1110#issuecomment-2882043181
> doc: testbed options

- flake/default.nix
- modules/vscode/update.py
```
Co-authored-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
```
Taken from https://github.com/nix-community/stylix/pull/1328#pullrequestreview-2868567933.
@MattSturgeon
> flake: add ruff formatter

- .github/workflows/backport.yml
- .github/workflows/check.yml
- .github/workflows/conflicts.yml
- .github/workflows/docs.yml
- .github/workflows/labels.yml
- .github/workflows/update-flake.yml
- .yamllint.yml
as mentioned in https://github.com/danth/stylix/pull/1103#issuecomment-2781087562
> stylix: yamlint ignore truthy for workflows

- .github/workflows/update-flake.yml
> ci: flake update 25.05

- modules/wayfire/hm.nix
See https://wayfire.org/
Ref: https://github.com/nix-community/stylix/pull/1371#discussion_r2117873450
maintainers: @_0x5a4
> wayfire: capitalize `humanName` value

- modules/ncspot/hm.nix
> ncspot: use mkTarget

- modules/swaylock/hm.nix
> swaylock: use mkTarget

- modules/yazi/hm.nix
A recent yazi update changed the way tabs are themed, so stylix needs to be updated accordingly.
> yazi: update tabs theming style

- stylix/palette.nix
https://github.com/nix-community/stylix/pull/1517#issuecomment-2989072279
> stylix: use config in literalMD

- modules/firefox/hm.nix
```
commit 32b2c1c85df463c7cf45bc99dd8825e9e22080cc
Date:   2025-06-25 23:21:56 +0200
firefox: simplify inherit formatting
commit 59d500f8644047aaed2af9675d00a62c86f880bb
Date:   2025-06-25 23:20:20 +0200
firefox: simplify derivation declaration
```
> firefox: simplify derivation and inherit declarations

- modules/rofi/hm.nix
Manual backport of https://github.com/nix-community/stylix/pull/1550 and https://github.com/nix-community/stylix/pull/1553.
> [release-25.05] rofi: backport 713f8dae3127 and 3a09d3f5cb94

- modules/ashell/hm.nix
Bug that got overlooked.
me im the maintanier :]
> ashell: fix use of opacity option

- modules/tmux/testbeds/tmux.nix
> tmux: add testbed

- modules/micro/testbeds/micro.nix
> micro: add testbed

- modules/zed/testbeds/zed.nix
> zed: add testbed

- doc/src/testbeds.md
> doc: fix testbed special option doc

- flake/default.nix
- flake/pre-commit.nix
these lists are getting kinda long and would be nice to have some consistency
> flake: sort pre-commit hooks and formatters

- modules/rio/testbeds/rio.nix
> rio: add testbed

- modules/rio/hm.nix
> rio: use mkTarget

- modules/neovim/testbeds/neovim.nix
- modules/neovim/testbeds/vim.nix
Related: #319 
@butzist @mightyiam @trueNAHO
> {neovim, vim}: add testbeds

- modules/wayfire/hm.nix
Fixes #1607 
@fierce-goose would you test to see if this PR fixes your issue?
@0x5a4
> wayfire: remove illegal `config.stylix` access

- modules/spicetify/spicetify.nix
> spicetify: use mkTarget

- modules/sxiv/testbeds/sxiv.nix
```
Fixes: 965865bc3603 ("sxiv: add testbed (#1190)")
```
@mateusauler
> sxiv: avoid downloading custom file in testbed

- modules/gtk/hm.nix
- modules/gtk/nixos.nix
> gtk: use mkTarget

- modules/plymouth/nixos.nix
- modules/plymouth/theme-script.nix
> plymouth: use mkTarget

- stylix/overlays.nix
> stylix/overlays: use isFunction

- modules/wayprompt/testbeds/wayprompt.nix
Added wayprompt testbed since #1222 resolved
@nukdokplex @panchoh
> wayprompt: add testbed

- doc/src/testbeds.md
- modules/bspwm/testbeds/bspwm.nix
- modules/gnome/testbeds/gnome.nix
- modules/hyprland/testbeds/hyprland.nix
- modules/kde/testbeds/kde.nix
- modules/mako/testbeds/mako.nix
- stylix/testbed/available-graphical-environments.nix
- stylix/testbed/default.nix
- stylix/testbed/graphical-environments/bspwm.nix
- stylix/testbed/graphical-environments/gnome.nix
- stylix/testbed/graphical-environments/hyprland.nix
- stylix/testbed/graphical-environments/kde.nix
- stylix/testbed/modules/application.nix
manual backport of https://github.com/nix-community/stylix/pull/1222
> [release-25.05] stylix: allow choosing testbed desktop 

- .github/workflows/check.yml
- .github/workflows/doc.yml
- .github/workflows/update-flake.yml
doesn't really matter but I'd prefer to use regular nix instead of determinate nix in our ci
> ci: use cachix install nix action

- flake/dev/flake.lock
- flake/dev/flake.nix
- modules/zen-browser/hm.nix
- modules/zen-browser/meta.nix
- modules/zen-browser/testbeds/zen-browser.nix
- modules/zen-browser/userChrome.css.mustache
- modules/zen-browser/userContent.css.mustache
- stylix/testbed/default.nix
This adds a target for the [Zen Browser](https://zen-browser.app/). Fixes https://github.com/nix-community/stylix/issues/1685
[locally](https://nix-community.github.io/stylix/modules.html#development-setup)
[commit convention](https://nix-community.github.io/stylix/commit_convention.html)
> zen-browser: init

- flake/dev/all-maintainers.nix
Improvement originally proposed in https://github.com/nix-community/stylix/pull/1053#discussion_r2226482725.
@awwpotato
> flake: leverage lib.flip

- modules/helix/testbeds/helix.nix
> helix: add testbed

- modules/yazi/hm.nix
This target doesn't have maintainers
> yazi: allow to set boldness of directory

- modules/fish/testbeds/fish-hm.nix
- modules/fish/testbeds/fish-nixos.nix
> fish: add testbeds

- .github/PULL_REQUEST_TEMPLATE.md
> ci: visually distinguish user description from PR template content

- flake/dev/flake.lock
- generated/all-maintainers.nix
- modules/anki/hm.nix
- modules/anki/meta.nix
- modules/anki/testbeds/anki.nix
- stylix/maintainers.nix
Adding an Anki target for home-manager
it uses the recolor mod to apply the colors
- no its not. the anki hm module only exists in unstable currently
> anki: init

- modules/anki/hm.nix
```
Fixes: 1b5e1c5642cf ("anki: init (#1801)")
```
---
> anki/hm: remove unused config argument

- .github/workflows/request-reviewers.yml
CC @trueNAHO @MattSturgeon 
```
Fixes: b4e1daad3b ("ci: request subsystem maintainers review (#1053)")
```
---
> ci: request-reviewers: add missing permission, fix modules path

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/change_option.yml
- .github/ISSUE_TEMPLATE/change_target.yml
- .github/ISSUE_TEMPLATE/new_option.yml
- .github/ISSUE_TEMPLATE/new_target.yml
- doc/src/modules.md
```
commit f6a351a444e9c3992c2573853f23e196899fb139
Date:   2025-08-09 20:37:55 +0200
treewide: add awwpotato to core maintainers list
.github/ISSUE_TEMPLATE/bug.yml           | 2 +-
.github/ISSUE_TEMPLATE/change_option.yml | 2 +-
.github/ISSUE_TEMPLATE/change_target.yml | 2 +-
.github/ISSUE_TEMPLATE/new_option.yml    | 2 +-
doc/src/modules.md                       | 1 +
5 files changed, 5 insertions(+), 4 deletions(-)
commit 3335202ed032912053e8132efc25b5cd4c8982b7
Date:   2025-08-09 20:39:22 +0200
ci: ISSUE_TEMPLATE: improve and match PR template
.github/ISSUE_TEMPLATE/bug.yml           | 59 +++++++++++++++++---------------
.github/ISSUE_TEMPLATE/change_option.yml | 29 …
```
> ci: ISSUE_TEMPLATE: improve and match PR template

- doc/src/commit_convention.md
```
commit ee128898d9d8daa1168c06a2d13266d41903099e
Date:   2025-08-27 00:42:43 +0200
doc/src/commit_convention: consistently indicate root directories
Fixes: 57d036d92283 ("doc: commit_convention: overhaul and formalize unspoken rules (#1717)")
doc/src/commit_convention.md | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
commit 98592e3c5926b67449e558d61a53e5a991d5dc16
Date:   2025-08-27 00:47:20 +0200
doc/src/commit_convention: add subsystem nesting commit example
doc/src/commit_convention.md | 3 +++
1 file changed, 3 insertions(+)
```
---
> doc/src/commit_convention: indicate root directory and add commit example

- modules/lazygit/hm.nix
https://nix-community.github.io/stylix/styling.html#window-managers
---
> lazygit: more consistent border colors

- flake.lock
- flake/dev/flake.lock
- flake/dev/flake.nix
- flake/dev/pre-commit.nix
Notably, this fixes the URL bar not being themed in recent Firefox versions with the Firefox GNOME Theme enabled. [1]
[1]: https://github.com/rafaelmardojai/firefox-gnome-theme/commit/26aa3233405166301b1a79c2bde008af309fba2e
---
> flake: update all inputs

- flake/dev/flake.lock
- modules/zen-browser/userChrome.nix
- modules/zen-browser/userContent.nix
> zen-browser: fix urlbar theming after zen 1.16b update
