nix-community/stylix

modules/alacritty.nix
Alacritty did not use the Stylix font setting, now it does.
=> Add font config to alacritty

flake.lock
Some custom schemes would not work with incompatible characters in the name. This should fix that.
=> Update base16 to include fix from SenchoPens/base16.nix#2

flake.nix, modules/bemenu.nix
Initial bemenu config with sane defaults. Sets the options via BEMENU_OPTS so they can also be overridden.
Includes optional settings such as ```fontSize``` and ```alternate```. These options can be set to adjust certain settings in bemenu.
=> Initial bemenu module

modules/gnome.nix
Gnome (at least Gnome 42 & 43) uses the dconf key `color-scheme` under `org/gnome/desktop/interface` to select dark mode. Additionally, the key for setting the wallpaper in dark mode is different to light mode (`picture-uri-dark` vs `picture-uri`). This is a simple patch for that.
Not sure if there is anything else to do here. Tested on my computer (using impermanence to wipe home so I don't think I was missing anything here). Light mode works correctly (if chosen).
=> Gnome Dark Theme

flake.nix, modules/i3.nix
I adapted the Sway module to support i3.
I changed some of the colors used for the bar since they do not display properly using my theme, `tomorrow-night-eighties.yaml`.  Maybe you want to revert that part, I don't know that much about the base16 standard anyway.
This is a great flake, btw.
Cheers!
=> feature: i3 module based on Sway module

modules/feh/hm.nix
=> Fix typo in a WM name: herbs{f⇒t}lu{⇒f}twm

README.md
To be properly syntax highlighted, Nix code block must be valid.
=> Fix nix code blocks in README

modules/vim/hm.nix
Otherwise it complains about ```E185: Cannot find color scheme 'base16-${themeSlug}'``` in line https://github.com/chriskempson/base16-vim/blob/3be3cd82cd31acfcab9a41bad853d9c68d30478d/templates/default.mustache#L13
=> vim/hm.nix: unlet colors_name to fix base16Scheme

modules/bspwm/hm.nix
There are a few things to discuss. The actual theme has been copied from [base16-builder](https://github.com/base16-builder/base16-builder), which had two templates, one for dark schemes and one for light ones. I kept the distinction but is it really something we want ?
Furthermore, I find that using `base08` as the focused window border color a bit too agressive, but I'd like other opinion.
Would close #39
=> Add bspwm module

stylix/hm/palette.nix, stylix/nixos/palette.nix, stylix/palette.json.mustache, stylix/palette.nix
Fix #48 
After a few tests I think I managed to get it to both:
- store the generated `palette.json` in the file system to prevent it from being garbage collected when the generated scheme is used
- yet not run the generation at all if it isn't used.
=> Prevent scheme generation from running when result is not used

modules/gnome/nixos.nix
Fix #43 while waiting for digga to solve it on their end. It may be a bit ugly, but that way we make sure there won't be a problem ever from setting `nixpkgs.overlays` in the gnome module.
=> Fix infinite recursion when _module.args.lib depends on nixpkgs.overlays

modules/alacritty/hm.nix, modules/bemenu/hm.nix, modules/dunst/hm.nix, modules/grub/nixos.nix, modules/gtk/hm.nix, modules/i3/hm.nix, modules/kitty/hm.nix, modules/mako/hm.nix, modules/qutebrowser/hm.nix, modules/rofi/hm.nix, modules/sway/hm.nix, modules/vim/hm.nix, modules/xresources/hm.nix, stylix/fonts.nix
To fix #35 and #59 , we need a way to specify font sizes. I think the best approach is to select a nomenclature of font sizes that could be reused by modules. Here I propose one such nomenclature to start discussions. Once the nomenclature is agreed upon, we can update the modules to use it.
=> Add options to set fonts

modules/i3/hm.nix
This PR fixes the `i3` module. Currently enabling this module makes the building of the configuration with the error 
```
error: cannot coerce an integer to a string
at /nix/store/mf4rkbfjpnj3kyqjxnsw4kgzjayvfvjs-modules/i3/hm.nix:14:40:
13|   in {
14|     names = [ "${fonts.sansSerif.name} ${fonts.sizes.desktop}" ];
|                                        ^
15|   };
```
=> i3: fix font size

README.md, flake.nix, stylix/darwin/default.nix, stylix/darwin/fonts.nix, stylix/darwin/palette.nix
=> feat: add darwinModules

flake.nix
Resolves a typo in the top level flake file that prevents usage as a darwin module.
=> Fix breaking typo in flake for darwin module

stylix/fromos.nix
As mentioned [there](https://github.com/danth/stylix/issues/67#issuecomment-1485683524), `fromOs` checks not only for the presence if the os config, but also if stylix is available in it. This enables using stylix as a home-manager-only module from within a nixos config.
=> Fix usage of hm module when system config does not use stylix

stylix/darwin/default.nix, stylix/nixos/default.nix
&lt;literal&gt; elemets get rendered, well, literally, on the static site.
See ¹ for the **devastating** effects.
Changed to native markdown style for proper rendering.
¹: https://danth.github.io/stylix/options/nixos.html#stylixhomemanagerintegrationfollowsystem
=> Fix markup on truth value

modules/vscode/hm.nix
This PR sets the vscode editor and terminal to use the monospace font configured with Stylix.
This also reformats the `userSettings` values as nested attribute sets.
=> vscode: Set editor and terminal font

modules/avizo/hm.nix, modules/mako/hm.nix, stylix/nixos/default.nix
This allows using master on 22.11 and on NixOS without the HM module. See #89 for design rationale.
=> Add options availability checks for avizo, mako and NixOS modules.

modules/zellij/hm.nix
Closes #111
Theme's bg value is used for selection, not the background so updated bg to base03 to address this
=> Fix Zellij selection highlight

modules/gnome/hm.nix
Some GTK applications (i.e. emacs-pgtk) will use the gnome interface settings in dconf to choose fonts.
Best set these in case something else does and you have to spend far too long figuring out why your emacs is using the wrong fonts.
=> Set fonts in gnome module.

palette-generator/Stylix/Palette.hs
The previous code to calculate the `accentDifference` for the fitness considered cases where a=b, so the minimal difference was always 0.
The new code explicitly excludes the index, so `a /= b` (except both entries were sampled to the same color, but that is what we want to punish here).
=> Fix accentDifference criterion for palette generation

modules/kde/hm.nix, modules/swaylock/hm.nix
It doesn't make much sense, and it breaks eval on darwin since
xdg.systemDirs is not available.
=> fix(modules/kde/hm): don't enable by default on darwin

modules/i3/hm.nix
home-manager changed slightly the way it handles fonts for i3, which broke the way stylix fonts were applied: this patch fixes that
=> fix i3 config for latest version of hm

flake.lock, stylix/nixos/fonts.nix
Gets rid of the warning due to fonts.fonts being renamed to fonts.packages
=> fix nixos module

modules/waybar/hm.nix
Specifying waybar font size in pixels leaves it looking weird because they end up a different size to most other places where it's specified in points. This fixes that for a more consistent look.
=> Change waybar font size to pt instead of px

modules/zathura/hm.nix
Redeclaring the default recolor configurations does not alter the theme, but requires using `lib.mkForce` to modify the default configurations.
For reference, the [zathurarc(5) man page](https://man.archlinux.org/man/zathurarc.5) states the following:
> recolor
>        En/Disables recoloring
>
>        • Value type: Boolean
>
>        • Default value: false
>
> recolor-keephue
>        En/Disables keeping original hue when recoloring
>
>        • Value type: Boolean
>
>        • Default value: false
=> feat(modules/zathura): remove default recolor configurations

modules/wezterm/hm.nix
Currently the stylix module for WezTerm sets the cursor fg and the cursor bg to the same color, rendering text under the cursor in programs such as neovim unreadable. This PR sets the cursor fg to base00, which should fix this problem
=> feat: fix wezterm cursor fg

modules/qutebrowser/hm.nix
Apply dark mode depending on `config.stylix.polarity`.
For reference, this was successfully tested with `config.stylix.polarity = "dark";` and `config.stylix.polarity = "light";`.
Closes: https://github.com/danth/stylix/issues/173
=> feat(modules/qutebrowser): apply dark mode depending on polarity

modules/hyprland/hm.nix
This resolve the issues introduce in Hyprland PR [#3522](https://github.com/hyprwm/Hyprland/pull/3522) which moved group variables out of general and into their own [section](https://wiki.hyprland.org/Configuring/Variables/#group).
=> Fix Group Variable Changes in Hyprland Module

modules/sway/hm.nix, stylix/cursor.nix, stylix/hm/cursor.nix, stylix/hm/default.nix, stylix/nixos/cursor.nix, stylix/nixos/default.nix
The main goal of this PR is to add cursor support to stylix as discussed in the linked issue.
An advantage of setting the cursor via stylix is that some DE/WM can also have the cursor theme set in their respective config.
See: change in `modules/sway/hm.nix`
Another advantage is that users wanting to style their system can do it all through stylix.
Even if home-manager is not used.
closes #120
=> feat: added cursor support and theming to stylix

stylix/hm/cursor.nix
`home.pointerCursor.x11.defaultCursor` is supposed to be the name of the cursor in the theme, not the name of theme. Setting in was breaking the default cursor on x11 application and desktop.
=> Fix default cursor in X11

modules/wezterm/hm.nix
There was an off-by-one shift in the ANSI palette. This change makes it be in sync with base16-kitty and base16-alacritty generators.
https://github.com/aarowill/base16-alacritty/blob/c95c200b3af739708455a03b5d185d3d2d263c6e/templates/default-256.mustache#L18 
https://github.com/kdrag0n/base16-kitty/blob/8fccf5271ceae858c0703478fc01e9899f0be322/templates/default-256.mustache#L20
=> wezterm: Fix color consistency

modules/vscode/hm.nix
Fixes settings not being greyed out by code when you view settings.json
See image
=> vscode: make settings strings

flake.lock, flake.nix, modules/alacritty/hm.nix, stylix/templates.nix
Since version 0.13.0 alacritty has switched to TOML config file format. For backwards compatibility this patch implements conditional template format depending on the package version.
Closes #214
=> alacritty: Use TOML template for recent versions

modules/qutebrowser/hm.nix
Font size isn't a part of its name.
Fixes an issue where qutebrowser uses the fallback font because the one with its size appended to its name doesn't exist.
=> qutebrowser: Fix font name and size handling

modules/k9s/hm.nix
The property `k9s.skin` has been renamed to `k9s.skins.skin` in
https://github.com/nix-community/home-manager/commit/020399c287afa853136b8089c315e238bf4b161d#diff-4683a1a711a4322a8063377f8e39708697d5f7b4ee5a1bc434fb91bc2d8541f7R18.
=> Fix k9s home-manager module

modules/qutebrowser/hm.nix
Use the correct `fonts.web.size.default` type to avoid the following error:
> Errors occurred while reading config.py:
>   While setting 'fonts.web.size.default': Invalid value '10pt' - expected a value of type int but got str.
Reference: https://qutebrowser.org/doc/help/settings.html#fonts.web.size.default
Follows: https://github.com/danth/stylix/pull/221
=> qutebrowser: use correct `fonts.web.size.default` type

modules/wezterm/hm.nix
This makes it easier to tell which tab is the active tab.
See the following image for an example:
The version of Wezterm running inside the virtual machine (with the yellow border) uses the current stylix styling, and the version outside the virtual machine uses my custom styling.
Current styling makes the inactive tabs have the same color as the terminal background, the proposed style flips this around.
I know this goes against the style guide, but I do believe it looks better this way.
(I am using the gruvbox colorscheme in case that matters)
=> fix(wezterm): Flip active and inactive tab colors

stylix/darwin/fonts.nix, stylix/darwin/palette.nix, stylix/fonts.nix, stylix/hm/fonts.nix, stylix/hm/palette.nix, stylix/nixos/fonts.nix, stylix/nixos/palette.nix, stylix/palette.nix
Fix dudplication in `stylix/*/fonts.nix` and `stylix/*/palette.nix`.
I haven't tested on macos, so if someone could test it there that would be great.
Fixes #234
=> Reduce duplication in stylix

flake.lock
This patch bumps base16.nix dependency to introduce support for the new tinted-theming/schemes repository, which is the nixpkgs repo for pkgs.base16-schemes. Support for `v0.11` spec has been implemented in https://github.com/SenchoPens/base16.nix/commit/b390e87cd404e65ab4d786666351f1292e89162a. Related issue https://github.com/SenchoPens/base16.nix/issues/9.
=> stylix: bump base16.nix

modules/mangohud/hm.nix
Added support for [mangohud](https://github.com/flightlessmango/MangoHud)
Image with base16-kanagawa and Fira. Something in the pipeline is causing extra blurring with screenshots, it's not present in game.
This one is a bit finnicky with its font handling; it requires an exact path to the font's .ttf, and the default configuration uses a super chonky font that the interface seems to be built around using.
=> Added Mangohud Support

modules/bat/hm.nix, modules/yazi/hm.nix
Add initial support for Yazi terminal file manager. The style is based on the upstream catppuccin themes, but with non-color subjective options removed.
Project repo: https://github.com/sxyazi/yazi
=> yazi: init hm module

.github/workflows/build.yml, .github/workflows/docs.yml, CONTRIBUTING.md
This should speed up Actions for repeated builds of the same package - for example the palette generator, which is rarely changed.
=> ci: use Magic Nix Cache

modules/nixvim/nixvim.nix
changed colorschemes.base.16.customColorScheme to colorschemes.base.16.colorscheme
this allows to get rid of the warning when building flakes
Nixvim change was made [here](https://github.com/nix-community/nixvim/commit/c2cd3cb7a13c0677c49f46d55a8c65b50b7d9431)
=> nixvim: changed property name to align with nixvim

modules/plymouth/nixos.nix
This goes against the chosen color scheme.
It was added to improve the interaction with `systemd-boot`, which cannot be themed, so there was not a sudden transition from unthemed to themed areas. However, keeping Plymouth unthemed only moves this transition later into the boot process.
A nicer solution can be achieved by setting `boot.loader.timeout = 0`, which effectively makes `systemd-boot` invisible unless a key is held down. This is not something we should include in Stylix, since it changes behaviour, but we can recommend it to users who want it.
=> plymouth: remove `blackBackground` option

modules/kde/hm.nix
As a non-KDE user it is rather irritating to receive logs about KDE not being installed. This change removes those logs.
=> kde: remove internal debugging logs

docs/src/tricks.md
The function implements a fairly popular feature and is pretty old, but never gets mentioned in the docs. In fact, I only found it by randomly going through the sources. As a result, a person I spoke to wrote the section above describing a re-implementation of the function, which does work but doesn't need to be the default approach.
This change will improve discoverability of the codebase and direct users to a more standardized implementation.
P.S. `base16-schemes` changed `catppuccin.yaml` to a couple of variant themes, which is represented in this commit.
=> doc: add mention of `lib.stylix.pixel` to tricks

stylix/palette.nix
Addresses: https://github.com/danth/stylix/pull/317#discussion_r1546389604
=> stylix: improve Bash expression

modules/plymouth/nixos.nix
Remove the 'substituteInPlace' function call because the new SVG [1] no longer contains the matching patterns.
[1]: https://github.com/danth/stylix/issues/334
Closes: https://github.com/danth/stylix/issues/337
Follows: https://github.com/danth/stylix/issues/334
Does removing the 'substituteInPlace' function call, intending to
> Reduce size
make the SVG look weird in other places in Stylix?
=> plymouth: 'substituteInPlace' does not match anything

flake.lock, modules/nixos-icons/nixos.nix
Refactors to `nixos-artwork` broke system builds with stylix by renaming files. Refactors in `nixpkgs` independently broke it by modifying the `sourceRoot` attribute.
---
`logo/white.svg` was renamed to `nix-snowflake-white.svg`
- https://github.com/NixOS/nixos-artwork/commit/ce919b818047ac481b8f1bfb9bee377e2b2889e2
---
Additionally, the source root of the derivation has been moved in the relevant nixpkgs PR
- https://github.com/NixOS/nixpkgs/pull/303068
This involves the `logo` directory being immutable in the patch phase now. Therefore, the previously used approach didn't work, so i've moved the patch phase into `applyPatches` on `src` directly rather than using mkDerivation's `patchPhase`. 
---
I've tested that stuff works fine on my machine and the produced artworks are indeed themed …
=> nixos-icons: `white.svg` -> `nix-snowflake-white.svg`

modules/nixos-icons/nixos.nix
It was removed upstream in this commit:
https://github.com/NixOS/nixos-artwork/commit/ce919b818047ac481b8f1bfb9bee377e2b2889e2#diff-335810e528842e1863df83d8f11332a3b8ae60a56cf2f8761a10f96b34bb5bbe
=> nixos-icons: remove rendered version of logo

modules/bat/hm.nix
Replaces the usage of the BAT_THEME environment variable in favor of the built in config parameter `theme`.
=> bat: use config instead of env variable

docs/src/installation.md
Good day!
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
=> doc: update NixOS wiki link

modules/gnome/colors.mustache
This was the color used for GNOME 45, and is consistent with other Stylix targets.
=> gnome: change panel background to `base01`

modules/gnome/hm.nix
stylix wasn't building the activation script on darwin until I disabled gnome.
I'm not sure if this is a problem for the master branch also, since I'm just using 23.11.
Without this, the error is caused by a failure to build ruby:
```
error: builder for '/nix/store/cnkvb40kaz71r3b2f3kas0v8mfzxc195-ruby3.1.4-ffi-1.10.0.drv' failed with exit code 1;
last 10 log lines:
> /nix/store/13wkzs6y9pm2g5v88cc0kngvlhxc3zp9-ruby-3.1.4/include/ruby-3.1.0/ruby/internal/attr/deprecated.h:36:53: note: expanded from macro 'RBIMPL_ATTR_DEPRECATED'
> # define RBIMPL_ATTR_DEPRECATED(msg) __attribute__((__deprecated__ msg))
>                                                     ^
> 4 warnings and 1 error generated.
> make: *** [Makefile:247: AbstractMemory.o] Error 1
>
> make failed, exit code 2
>
> Gem files …
```
=> gnome: don't enable by default on darwin

README.md
Should we mention [this independent YouTube guide](https://youtu.be/ljHkWgBaQWU) considering that it may become outdated?
*Huge thanks for the shoutout, @vimjoyer!*
=> doc: mention YouTube video guide

docs/src/installation.md
Fix #381
Actualize link for `Installing Home Manager as a NixOS module` in `docs/src/installation.md`
=> doc: update `Installing Home Manager as a NixOS module` link

modules/waybar/hm.nix
Using 0xProto as font-family breaks waybars style.css (Error: `Expected a string`). This fixes it.
=> waybar: put font-family string in quotes.

modules/gnome/nixos.nix
Using the internal `mkEnableTarget` function encapsulates the target enabling logic, which simplifies the https://github.com/danth/stylix/pull/244#issuecomment-2132260027 implementation.
Follows: 679a80676840185cbc72a3751ccdac169477c21a
=> gnome: use internal `mkEnableTarget` function

modules/console/nixos.nix
I'm not entirely clear on why the console colors currently work the way they do, but in my opinion it's better to repeat than scramble the 2nd-6th colors most terminal apps seem to look a lot better with this.
=> console: adjust colors

stylix/target.nix
Standardize the `stylix.autoEnable` and `stylix.mkEnableTarget` documentation to simplify its documentation extension in https://github.com/danth/stylix/pull/244.
=> stylix: standardize `autoEnable` and `mkEnableTarget` documentation

stylix/target.nix
Simplify the `stylix.mkEnableTarget` documentation to simplify its documentation extension in https://github.com/danth/stylix/pull/244.
> Due to some targets not being enabled by default with `stylix.mkEnableTarget`, the documentation incorrectly generates `Default: false` in some cases with https://github.com/danth/stylix/pull/399. Resolving this involves manually extending [`docs/settings.nix`](https://github.com/danth/stylix/blob/00a11ba2f0b52f761c0bc77daebb00cb4d44ba09/docs/settings.nix) or enabling all targets by default with `stylix.mkEnableTarget`.
>
> -- https://github.com/danth/stylix/issues/400
=> stylix: simplify `mkEnableTarget` documentation

modules/vim/hm.nix, modules/wpaperd/hm.nix
This PR exposes the base16 colourscheme by using a Vimscript dictionary
This change allow users to acess the colours within their Vim/NeoVim config, which 
is useful for example to set highlight groups for specific plugins
- Defined a base16 colour scheme in a Vimscript dictionary
- Exposed the color scheme via a global Vimscript variable
```vimscript
g:colors['base00'] " Yields the hex code of base00
```
Or using lua
```lua
vim.g.colors.base00 -- Yields the hex code of base00
```
=> vim: interface colorscheme

modules/sway/hm.nix, stylix/palette.nix
adds option for which type of scaling the background image should get
currently this only applied sway, but should probably be applied to the other WM/DE also supported in stylix, if someone knows how to configure it for the rest of them i'd appreciate the help
i set the default to be fill, the one the previous option used in sway by stylix, not sure if this should be the right default, as it seems some of the other WM/DEs have different default configs (eg gnome with zoom).
also not sure if "scaling mode" is the right term for this, it was what the sway man pages used.
=> add background image scaling option

modules/zathura/hm.nix
This adds transparency back to the zathura module as discussed. I'm new to nix, so let me know if there's something to improve :).
Closes: #392
=> zathura: add transparency to highlight colors

modules/gtk/gtk.mustache
`base0D` is 100% more sensible, it is usually a blue color, and the accent color of gtk is used for links and selections, for which blue makes the most sense.
=> gtk: change accent color

docs/src/styling.md, modules/bspwm/hm.nix, modules/hyprland/hm.nix, modules/i3/hm.nix, modules/sway/hm.nix
This makes the most sense to me, I feel like blue is the "most default" accent color. As for groups, the active and inactive colors should be the same, since they are still windows, while the locked active color is a slightly modified active color (at least in catppuccin, it's teal instead of blue).
=> treewide: change window manager style guide

stylix/testbed.nix
Otherwise, the testbeds don't show any theming.
Follows #244
=> stylix: enable Stylix in testbeds

modules/swaylock/hm.nix
This was added in 2022. Not only is the option now in a stable release, but also any releases where it doesn't exist are most likely deprecated by now.
=> swaylock: remove `optionalAttrs`

flake.lock, flake.nix
While exploring the code I noticed that the current base16-vim input hasn't been updated in 2 years.
It appears to have been forked into the tinted-theming project. Although not an explicit fork the contributor list and some readme content appears to match.
I haven't tested this out myself yet since I'm using nixvim which doesn't use this input.
=> vim: use maintained fork of base16-vim

modules/zellij/hm.nix
Brings the Zellij theme more in-line with the default theme. For dark themes, Zellij's shades go from darkest to brightest: black < bg < fg < white. The exact shades used for the four is based on the standard mapping of the 8 primary colors to ANSI's 4 shades.
This makes the tab and status bars significantly more readable.
This does not account for light themes, and Zellij dynamically switches between white and black for certain elements depending on the polarity, however I couldn't find of other modules that accounted for polarity, so I left it for a future change. I also did not rename the accents to their semantic names, though it would be simple to do.
=> zellij: fix black & white

stylix/darwin/default.nix
- Fix [opacity issue](https://github.com/danth/stylix/issues/440)
- Fix `fonts.fonts` has been renamed to `fonts.packages`
- Fix `fonts.fontDir` has been deprecated
This PR adresses the several issues:
Firstly, the opacity issue on darwin [opacity issue](https://github.com/danth/stylix/issues/440).
And secondly, the deprecation of the fontDir option as well as the renaming of `fonts.fonts` to `fonts.packages`
=> Fix opacity darwin and rm fontDir + rename fonts.fonts to fonts.packages

modules/hyprland/hm.nix
Adds colors to the groupbars in hyprland.
Groupbar:
=> hyprland: add groupbar colors

modules/nushell/hm.nix
Nushell: fix typo
separator misspelled, resulting in inconsistent theming in nushell.
=> nushell: fix separator typo

modules/fzf/hm.nix
home-manager provides a programs.fzf.colors option to provide colors. This module basically reimplemented the logic home-manager has as well.
@examosa You created the first PR, maybe you want to look over this?
=> fzf: use home-manager color options

docs/src/configuration.md
https://github.com/NixOS/nixpkgs/issues/285671
>The base16-schemes package uses the tinted-theming/base16-schemes repository,
>which has now been archived by the owner in favor of tinted-theming/schemes
=> doc: update tinted-theming repo link

modules/ncspot/hm.nix
Adds stylix target for [ncspot](https://github.com/hrkfdn/ncspot)
Example with tokyonight-dark theme:
=> ncspot: init

modules/vesktop/template.mustache
Some generated text colors in dark themes are too close to the background color, making it hard to read.
I've tested these changes with many gruvbox dark variants, light-medium, and catpuccin dark variants.
Before:
After:
Closes: https://github.com/danth/stylix/issues/474
=> vesktop: improve contrast

modules/kde/hm.nix
Revert commit 6bbae4f85b89 ("kde: apply Qt theme on non-KDE systems and add Qt6 support (#367)") due to unexpected issues.
Follow-up work is tracked in https://github.com/danth/stylix/issues/489.
Closes: https://github.com/danth/stylix/issues/480
Closes: https://github.com/danth/stylix/issues/485
Closes: https://github.com/danth/stylix/issues/487
Cc: @Jackaed, @danth
=> kde: revoke Qt6 and non-KDE Qt theme support

modules/neovim/hm.nix
Fixes an error introduced by 3499dff34d2ac683bcb011fb2f2075d75336822a
=> neovim: fix incorrect use of `mkIf`

modules/nixvim/nixvim.nix, stylix/palette.nix
Add soft deprecation dates to guide the hard deprecation transitions.
Fixes: 3567250ba049 ("Properly warn users that stylix.palette.* has been removed")
Fixes: 94aa0fc0fbe9 ("nixvim: rename transparency options to camelCase (#497)")
=> treewide: add soft deprecation dates

modules/kde/testbed.nix
Rename the deprecated `services.xserver.displayManager.sddm.enable` option to `services.displayManager.sddm.enable`, following https://github.com/NixOS/nixpkgs/pull/291913.
=> kde: rename deprecated option

.github/dependabot.yml
> [GitHub] Actions are often updated with bug fixes and new features to make automated processes more reliable, faster, and safer. When you enable Dependabot version updates for GitHub Actions, Dependabot will help ensure that references to actions in a repository's workflow.yml file and reusable workflows used inside workflows are kept up to date.
>
> [...]
>
> If a more recent version of the action is available, Dependabot will send you a pull request that updates the reference in the workflow file to the latest version.
>
> -- GitHub Docs
>    https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
Link: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-depe …
=> ci: add Dependabot to keep GitHub Actions up-to-date

flake.lock, flake.nix, stylix/systems.nix
This patchset re-adds the `flake-utils` dependency removed in commit ff5da2914cfc ("Remove dependency on flake-utils :heavy_minus_sign:").
> [!NOTE]
>
> These commits should be merged individually, **not squashed**, to ensure a clear and easily reversible changelog. In case of change requests, review the commits separately.
=> stylix: re-add `flake-utils` dependency

flake.lock, modules/gnome/nixos.nix
Rename the deprecated `pkgs.gnome.gnome-backgrounds` package to `pkgs.gnome-backgrounds`, following https://github.com/NixOS/nixpkgs/commit/6e8760f7f7121128e2037db44915a4a5450b6e67.
Cc: @knoopx
=> gnome: rename deprecated `pkgs.gnome.gnome-backgrounds` package

modules/fish/prompt.nix
This check was incorrectly brought over from 'https://github.com/tomyun/base16-fish/issues/7#issuecomment-963376055' as the base16_theme environment variable is not used in Stylix.
Closes #538.
=> fish: remove incorrect env check

modules/hyprland/hm.nix
See https://github.com/danth/stylix/issues/542#issuecomment-2324323870
I have tested this in my own configuration, and Hyprpaper is no longer installed.
=> hyprland: only enable hyprpaper when hyprland is installed

flake.lock, modules/gnome/nixos.nix
Once with this PR https://github.com/NixOS/nixpkgs/pull/338583 got merged the gnome-shell overlay did not have any effect, moreover stylix flake stopped building on the latest master of nixpkgs.
This PR removed the outer gnome overlay and let the gnome-shell be modified as a standalone package.
Note: this is the first time I look at stylix codebase and I might have overlooked things. If you think of something missing please ping me.
Edit: The error I got when using the latest nixpkgs master branch:
```
error:
… while calling the 'head' builtin
at /nix/store/gi5jqh2i4djgqz45vljnpz0bhnxdafgv-source/lib/attrsets.nix:1575:11:
1574|         || pred here (elemAt values 1) (head values) then
1575|           head values
|           ^
1576|         else
… while evaluating the attribute 'value'
at …
```
=> gnome: moved gnome-shell overlay outside its gnome packages umbrella

modules/emacs/hm.nix
The emacs module currently doesn't set the font size, only the colours and font family. This PR sets it to `sizes.terminal` (taking a lead from the `guifont` setting in the `vim` module) using `font-spec`, which is a more flexible way to specify fonts in elisp. To indicate the size is points it needs to be a floating point value.
=> emacs: explicitly set font size

modules/emacs/hm.nix
If the size is expressed as a string, Emacs calls bloody murder:
invalid font property (:size . "14.000000")
Refs: 35233f929629c8eb64e939e35260fc8347f94df9
=> emacs: fix spurious quotes around :size arg

modules/wofi/hm.nix
Without a unit specified in wofi's `style.css`, it emits a warning and defaults to using pixels, which (on my screens anyway) results in the font being larger than intended. This explicitly sets the unit to `pt`.
=> wofi: specify a unit (pt) for font size

modules/i3status-rust/hm.nix
I had these colors from stylix set in my hm configs. But I figured I should add them to the stylix repo for other users of i3status-rust!
Kept it short and sweet but let me know if anything is needed :)
=> i3status-rust: init

modules/wezterm/hm.nix
By default, the fancy tabbar doesn't respect colorschemes, see https://github.com/wez/wezterm/issues/2615. But I've found that if you set the tabbar colors in the config.lua in addition to the colors/stylix.toml file, the fancy tabbar does respect the colors set.
Here's what it ends up looking like:
This change doesn't affect the retro tab theming, which I made sure to test.
My only doubt is whether I should have kept the `use_fancy_tab_bar = false,` line. Keeping this line will keep everyone's current wezterm config unchanged, but will differ from wezterm's default look. Removing the line will make it so everyone who uses stylix and doesn't have `use_fancy_tab_bar = false,` in their config will now have the fancy tabbar all of a sudden, but it is in line with the default wezterm look. I …
=> wezterm: support fancy_tab_bar

flake.lock, flake.nix, modules/foot/hm.nix, modules/kitty/hm.nix, modules/tmux/hm.nix, stylix/templates.nix
```patch
NAHO (2):
stylix: rename base16-kitty input to tinted-kitty
stylix: rename base16-foot and base16-tmux inputs
flake.lock           | 104 +++++++++++++++++++++----------------------
flake.nix            |  30 ++++++-------
modules/foot/hm.nix  |   2 +-
modules/kitty/hm.nix |   2 +-
modules/tmux/hm.nix  |   2 +-
stylix/templates.nix |   6 +--
6 files changed, 73 insertions(+), 73 deletions(-)
```
=> stylix: rename `base16-foot`, `base16-tmux`, and `base16-kitty` inputs

modules/nixvim/nixvim.nix, stylix/palette.nix
This patchset includes:
- `treewide: generate deprecation warnings`
- `treewide: declare end-of-life for deprecated options`
- `stylix: remove deprecated options reaching end-of-life`
> [!NOTE]
>
> These commits should be merged individually, **not squashed**, to ensure a clear and easily reversible changelog. In case of change requests, review the commits separately.
=> treewide: update option deprecations

modules/regreet/nixos.nix
This is my first PR to this repo, so I hope to receive some guidance on making it compliant with the contribution guide.
It adds a styling module for ReGreet, a Greetd front-end that Nixpkgs already has a module for.
!! `regreet.mustache` is an exact copy of `gtk.mustache` !!
Since regret is styled by a typical gtk4 CSS, this works pretty well, despite it being redundant.
I chose to not reference `gtk.mustache` because in the future someone with more styling sense than me might come along and make this even fancier. Unfortunately, I could not find any custom CSS on GitHub to use as reference myself.
=> regreet: init

modules/spicetify/hm.nix, modules/spicetify/nixos.nix, modules/spicetify/spicetify.nix
Creates a theme for Spotify, when used in combination with [spicetify-nix](https://github.com/Gerg-L/spicetify-nix).
=> spicetify: init

modules/spicetify/spicetify.nix
Disables spicetify theme sidebar configuration to resolve an incompatibility notification on Spotify startup
=> spicetify: fix sidebar incompatiblity

modules/fuzzel/hm.nix
Removing dpi-aware setting to allow scaled systems to use fuzzel properly. Tested locally with no unexpected side effects
=> fuzzel: remove dpi-aware = "no"

modules/bat/base16-stylix.mustache
I would like to propose a small change in a template for bat. The change improves coloring of man pages showed using bat.
It's a known issue that most of themes don't well support bat and man  as described in the [caveats section](https://github.com/eth-p/bat-extras/blob/master/doc/batman.md#caveats).
I've tested the change with the 24.05 release, but create the PR for the `master` branch. The tested change can be find at the [branch](https://github.com/JanOlencki/stylix/tree/batman-fix-backport-24.05)
You can find the result in the picture below.
=> Improve coloring manpages with bat

modules/forge/hm.nix, modules/forge/stylesheet.css.mustache
Adds border colors to the Forge GNOME extension. It basically makes all focused window borders blue. In contrast to the style guide, unfocused windows don't have a border, because I couldn't find a setting for that.
=> forge: init

flake.lock
Closes: https://github.com/danth/stylix/issues/567
Link: https://github.com/danth/stylix/pull/588
=> stylix: bump tinted-kitty input

flake.lock, flake.nix
```
stylix: downgrade and lock tinted-kitty input
Downgrade and lock the tinted-kitty input to avoid upstream breaking
changes.
Considering that Stylix eventually re-implements tinted-kitty's
functionality [1], it might be easiest to lock this input to avoid
wasted maintenance effort.
This downgrade revokes commit 5699ba97c604 ("stylix: bump tinted-kitty
input (#588)"), which resolved the issue "bug: inconsistent color
between terminals (foot & kitty)" [2] by pulling [3]. Since the desired
commit [3] follows the commit introducing the breaking changes [4], it
cannot be pulled without resolving these breaking changes.
[1]: https://github.com/danth/stylix/issues/534
[2]: https://github.com/danth/stylix/issues/567
[3]: https://github.com/tinted-theming/tinted-kitty/commit/292c7175f7892b786277 …
```
=> stylix: downgrade and lock tinted-kitty input

modules/vesktop/template.mustache
Some vesktop or discord update broke recoloring of forum channels.
Before: ![image](https://github.com/user-attachments/assets/84ff32e6-af70-4274-96dd-e85bfdef2171)
After: ![image](https://github.com/user-attachments/assets/6bf492f9-d7f1-4c85-892a-5f38ade2c740)
=> vesktop: recolor forum channels

modules/neovim/hm.nix, modules/nixvim/nixvim.nix
Switches both the neovim and nixvim modules to use mini.base16.
Closes #535
=> neovim: use mini.base16 for colorscheme

modules/hyprland/hm.nix
https://github.com/hyprwm/Hyprland/commit/d1638a09bacd84b994de3f77746b74f427b9d41e
=> hyprland: adapt breaking changes

modules/hyprland/hm.nix
```
Revert commit 762c07ee10b3 ("hyprland: adapt breaking changes (#605)"),
which falsely attempted to address a Hyprland breaking change [1] which
is not yet available as a Hyprland release or Nixpkgs package, and
therefore not available through Stylix's inputs.nixpkgs input.
To address the future breaking change, update Stylix's inputs.nixpkgs
input after the next Hyprland release is included in
nixpkgs/nixos-unstable.
[1]: https://github.com/hyprwm/Hyprland/commit/d1638a09bacd84b994de3f77746b74f427b9d41e
Link: https://github.com/danth/stylix/pull/608
```
=> hyprland: revert attempt to address unavailable Hyprland breaking change

flake.nix
This solves #571. But since this is only a temporary fix, it does not need to be merged. See https://github.com/SenchoPens/base16.nix/issues/15
There may be a way to do this better, but at least it works for me.
=> foot: disable faulty check

flake.lock
```
Link: https://github.com/danth/stylix/pull/613
Fixes: 6863412636c8 ("foot: disable faulty check (#576)")
```
=> stylix: update tinted-foot input

modules/zellij/hm.nix
Zellij supports both adding themes via your primary config, or adding a theme into a themes folder. This PR writes the theme into the themes folder instead of the default config.
This is useful because you may not be able to write your Zellij config via home manager (Nix KDL support is currently very limited, at least I couldn't figure out how to get the new non-overlapping modes default config written in Nix).
So if this is the case you end up needing to supply your own `~/.config/zellij/config.kdl`, which overrides the home manager one with Stylix in it.
By writing to a theme file you avoid this problem entirely.
Red color was also changed to `base01` due to previous contrast issues mentioned in #486
=> zellij: write theme file instead of writing theme into config

flake.lock, modules/hyprland/testbed.nix
This adds a testbed for Hyprland.
Note that when running the VM, you need to log in as `guest` and then type `Hyprland` to start Hyprland.
Also, there are currently some graphical bugs caused by the VM itself. https://github.com/hyprwm/Hyprland/issues/1056 may be relevant.
=> hyprland: add testbed

docs/src/tricks.md, stylix/autoload.nix, stylix/darwin/default.nix, stylix/hm/default.nix, stylix/nixos/default.nix, stylix/testbed.nix
Apparently `../modules` is creating a separate derivation that contains only that folder, so it's now separate from the  flake source. But this transient derivation isn't mentioned explicitly anywhere in the flake outputs. It makes it impossible to target those modules in `disabledModules` directive.
For example, after this change is applied, users can solve issues like https://github.com/danth/stylix/issues/577 locally, by just adding the following snippet to their configuration:
disabledModules = [ "${inputs.stylix}/modules/regreet/nixos.nix" ];
=> Don't split autoloaded modules into a separate derivation

modules/hyprlock/hm.nix
This value needs to be a string, not a path, to be set succesfully.
=> hyprlock: use a string instead of a path for `background.path`

modules/vim/hm.nix
Similar to the #644 PR, it seems the vim module also needs a `target` attribute in order to not break on build.
=> Fix build error in vim module

flake.lock, modules/kubecolor/hm.nix
Adds support for [kubecolor](https://github.com/kubecolor/kubecolor) tool.
**Note:** had to update `home-manager` in `flake.lock` file, as `kubecolor` is a recent addition, and currently lives only in `master` branch.
=> kubecolor: init

modules/sway/hm.nix
Closes: https://github.com/danth/stylix/issues/648
Fixes: 07795247c2db ("Add cursor support (#172)")
Link: https://github.com/danth/stylix/pull/654
---
@saygo-png, can you confirm this resolves https://github.com/danth/stylix/issues/648.
=> sway: handle cursor names containing spaces

modules/hyprland/hm.nix
This patchset contains the following commits:
- **hyprland: add hyprpaper.enable option**
- **hyprland: structurally separate unconditional and conditional settings**
- **hyprland: inline single-use variable**
- **hyprland: reduce local variable scopes**
- **hyprland: remove with statement**
Closes: https://github.com/danth/stylix/issues/499
---
Note that I have not actually tested this PR, and as such it may contain silly errors.
This PR has been tested:
> > Yup, just tested on your branch and everything hyprpaper was removed upon rebuilding once it was set to false. And once adding hyprpaper manually, my wallpaper script is working perfect so far. So seems to be working to me.
>
> -- https://github.com/danth/stylix/issues/499#issuecomment-2282218553
=> hyprland: add hyprpaper.enable option and improve code

.github/workflows/backport.yml
This is heavily based on [the workflow used by Nixpkgs](https://github.com/NixOS/nixpkgs/blob/2ab6f6d61630889491f86396b27a76ffb6fbc7bb/.github/workflows/backport.yml).
It allows us to automatically create backport pull requests by labelling the original pull request.
Labels should use the format `backport «branch»`.
=> ci: implement automated backports

docs/src/commit_convention.md
```
Remove legacy documentation about commit message conventions predating
the standardized format introduced in commit bf31640f49cb ("doc: specify
commit message format") on 2024-01-23, with the final GitMoji usage in
commit 5a7f3f15ccc2 ("Add guide for creating modules :memo:").
```
=> doc: remove documentation about legacy commit conventions

.github/workflows/build.yml
Following the discussion in #671, this will fail the CI workflow if an input in `flake.lock` is updated to a revision which isn't on the branch specified in `flake.nix`. This prevents accidentally updating the release branch to use an unstable Nixpkgs revision.
=> ci: ensure branch names in `flake.lock` match `flake.nix`

modules/feh/hm.nix, modules/feh/nixos.nix, modules/gnome/hm.nix, modules/grub/nixos.nix, modules/regreet/nixos.nix, modules/swaylock/hm.nix, modules/wpaperd/hm.nix
Fixes #677 
Presently, `stylix.imageScalingMode` only has an effect on sway. This PR implements it for
- swaylock
- wpaperd
- GNOME
- feh
- grub
- regreet
It _seems_ like setting this for KDE isn't possible with our current methods.
=> Further implementation of `stylix.imageScalingMode`

modules/vscode/hm.nix
The font sizes shouldn't be rounded when converting `pt` to `px`. For example, `13.333` will look bigger than `13` and smaller than `14`
In my configuration, the rounding causes my editor fonts to look *really* small compared to my standalone terminal.
=> vscode: don't round font sizes

modules/cava/hm.nix
This PR inits the `cava` target which doesn't apply any changes by default yet. However, it adds a `stylix.targets.cava.rainbow.enable` option for a rainbow gradient, which is often used with this application.
Before | After
-------- | ------
I'm not sure how and whether to handle gradients with stylix, but I used the colors for images from the style guide and sorted them rainbow-ishly. If there are more applications using gradients like this, it would make sense to add a stylix wide option to define the preferred gradient or solid color.
=> cava: init with rainbow theme

modules/xresources/hm.nix, stylix/fonts.nix
Font sizes are currently treated as `pt`, so they should allow floating point values in addition to integer values. The documentation is also updated to make this clear.
I've done my best to check and adjust affected modules, but I may have missed some so extra eyes would be appreciated.
=> Allow floats for font sizes

docs/src/tricks.md
This fix the following warning 
```
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"
```
Generated by the command
```shell
magick convert -size 1920x1080 xc:$COLOR $out
```
=> Fix deprecated warning for using `magick convert` instead of `magick`

modules/gtk/hm.nix
Resolves #465 and adds support for theming Flatpak apps by making the GTK theme accessible to them. This support can be enabled using `targets.gtk.flatpakSupport.enable`. See [this article](https://itsfoss.com/flatpak-app-apply-theme/) for an in-depth explanation of Flatpak theming.
To enable Flatpak theming support, this module writes to Flatpak's overrides configuration which currently does not have a dedicated Home Manager option. It might therefore create conflicts with other modules that write directly to this file, such as those defined by `nix-flatpak`.
<details><summary>Here are some Flatpak apps with a Catppuccin GTK theme.</summary>
</details>
See https://github.com/danth/stylix/issues/465#issuecomment-2552492498 and replies for previous discussions on this matter.
=> gtk: add support for theming Flatpak apps

modules/alacritty/testbed.nix, modules/chromium/testbed.nix, modules/emacs/testbed.nix, modules/firefox/testbed.nix, modules/foot/testbed.nix, modules/gedit/testbed.nix, modules/kitty/testbed.nix, modules/qutebrowser/testbed.nix, modules/vesktop/testbed.nix, modules/vscode/testbed.nix, modules/wezterm/testbed.nix, modules/zathura/testbed.nix, stylix/testbed.nix
This PR extends the current testbeds to also include individual GUI applications, rather than just desktop environments. This is useful for a number of reasons (which also relate to the testbed system as a whole):
- Easy to preview a pull request without changing your real configuration. Just type `nix run github:«owner»/«repository»/«branch»#testbed-«application»-«polarity»`.
- Compared to local installation, testbeds have their filesystem reset between rebuilds, so every test simulates a fresh installation. This can help to pick up on cases where there are manual steps required for a module to be effective.
- CI tests for successful evaluation. The extent to which this actually confirms that the configuration is valid can vary.
The application testbeds are currently based on GNOME. This …
=> treewide: add application testbeds

modules/foot/testbed.nix
This was [recently changed upstream](https://codeberg.org/dnkl/foot/commit/c8185aec1d36df3aa60001a0b3a0fbd49d11df18).
This is the cause of [this failed workflow run on `master`](https://github.com/danth/stylix/actions/runs/12539341620).
=> foot: update desktop file name in testbed

stylix/palette.nix
Adds explanations of each option for imageScalingMode. The explanations follow the behavior in swaybg but should be mostly universal.
=> doc: document imageScalingMode options

flake.lock, flake.nix
Update the `nixpkgs` `ref`, following the conversation from:
> > Keep in mind that the Nixpkgs PR has to land into `nixpkgs-unstable` (https://nixpk.gs/pr-tracker.html?pr=368404) because that is what we are tracking:
> >
> > https://github.com/danth/stylix/blob/963e77a3a4fc2be670d5a9a6cbeb249b8a43808a/flake.nix#L45
>
> The package PR has landed onto `nixpkgs-unstable`, but we gotta wait for the HM merge. I guess they wait for `nixos-unstable`:
>
> https://github.com/nix-community/home-manager/blob/10e99c43cdf4a0713b4e81d90691d22c6a58bdf2/flake.nix#L4
>
> Is there a reason why `nixos-unstable` isn't tracked in stylix?
>
> -- [arunoruto, "ghostty: init"](https://github.com/danth/stylix/pull/703#issuecomment-2565005819)
=> stylix: point nixpkgs input to more conventional nixos-unstable ref

flake.lock, modules/ghostty/hm.nix, modules/ghostty/testbed.nix
Ghostty just came out, and I wanted to try it out right away!
If I am gonna do this, I could also do it the right way from the start so I can share my config. Here is my current progress. Feel free to chime in with corrections :D
Colorscheme is derived by comparing cattpuccin macchiato from their [official ghostty repo](https://github.com/catppuccin/ghostty/blob/main/themes/catppuccin-macchiato.conf) and the [tera file for compiling the theme](https://github.com/catppuccin/ghostty/blob/main/ghostty.tera), and the [base16 version of the theme](https://github.com/tinted-theming/schemes/blob/spec-0.11/base16/catppuccin-macchiato.yaml). They named everything nicely! The only things missing are:
- the pink color -> I used flamingo instead (base0F), close enough
- the subtext colors were not …
=> ghostty: init

modules/yazi/hm.nix, modules/yazi/testbed.nix
Things done:
- ~Bumped `nixpkgs` flake input (as per suggestion https://github.com/danth/stylix/pull/719#issuecomment-2567152978).~
- Added a simple testbed for `yazi`.
- Reversed `marker_selected` and `marker_copied` to match upstream themes. See issue https://github.com/danth/stylix/issues/604 and upstream [template](https://github.com/yazi-rs/flavors/blob/fc8eeaab9da882d0e77ecb4e603b67903a94ee6e/scripts/catppuccin/template.toml#L17-L20).
- Migrated highlight colors to mnemonics for improved readability. This greatly simplifies matching our theme to the upstream one based on catppuccin. This will be very helpful when migrating to support yazi 0.4.0 breaking changes (https://github.com/danth/stylix/issues/683). Migration script is provided in the commit message.
- Adapted to `0.4.x` yazi …
=> yazi: add testbed, adapt to 0.4.x changes

modules/kde/hm.nix
Fixes: #422, #350 and #340
Based on: https://github.com/danth/stylix/pull/547
KDE theming uses CLI tools which require D-Bus and Plasma session. Instead of breaking home-manager activation, this PR creates a KDE "AutostartScript" that applies the Global Theme during the startup of Plasma.
It's basically a desktop entry in the autostart directory which has a special tag X-KDE-AutostartScript that tells Plasma to start it early. The X-KDE-AutostartScript is probably not required, since I noticed that plasma-manager is doing something similar without it.
This PR has the same scope as https://github.com/danth/stylix/pull/547 but is better because the AutostartScript will run no matter how home-manager is installed - be it as a NixOS module or standalone or some custom solution. The approach …
=> Fix plasma activation

docs/src/installation.md
Using the wrong branch is a very common cause of questions, due to it not being mentioned anywhere in the documentation. See #721, #681 for some recent examples.
=> doc: draw attention to release branches

flake.lock, flake.nix, modules/zed/hm.nix, stylix/templates.nix
Add [zed editor](https://zed.dev) module support.
Closes: https://github.com/danth/stylix/issues/348
=> zed: added zed hm module

.github/workflows/check.yml
```
Run the CI on PRs, while preventing it from running twice for non-fork
PRs by limiting the push event to protected branches. [1]
This restores the workflow trigger that was accidentally modified in
commit 2b85a562355c ("ci: simplify workflows").
[1]: https://github.com/danth/stylix/pull/749#issuecomment-2573437938
Fixes: 2b85a562355c ("ci: simplify workflows")
```
=> ci: run CI on PRs and limit push event to protected branches

flake.lock, flake.nix, modules/firefox/hm.nix, modules/firefox/userChrome.mustache, stylix/templates.nix
This adds the `firefoxGnomeTheme.enable` option which installs the [Firefox GNOME theme](https://github.com/rafaelmardojai/firefox-gnome-theme) with the Stylix palette on Firefox derivatives. Note that the new `modules/firefox/userChrome.mustache` is mostly a syntactically modified version of `modules/gtk/gtk.mustache`.
<details>
<summary>Preview the Firefox GNOME theme on LibreWolf with other slight modifications.</summary>
Note the similarity to the [GNOME Web](https://apps.gnome.org/Epiphany/) browser.
</details>
=> firefox: add firefox-gnome-theme

flake.lock, flake.nix, modules/firefox/hm.nix, modules/firefox/userChrome.mustache, stylix/templates.nix
Manual backport of #702, due to merge conflicts.
Tested this locally and all is working.
=> [release-24.11] firefox: add firefoxGnomeTheme.enable option

modules/regreet/nixos.nix
ReGreet will choose dark colors from the GTK theme if we instruct it to do so.
ReGreet uses the global GTK theme if the environment is set the default Nixpkgs configuration takes care of that so extraCss will be left free for actual user overrides.
For regreet to be themed correctly, users need to start regreet with dbus environment. Nixpkgs does this by default but I don't know how to help people with special configurations.
Motivated by #690
=> regreet: respect dark mode and do not set extraCss

.github/workflows/backport.yml
```
commit 0db7d025edaae15dd603c7c9874212a052ca328f
Date:   2025-01-06 23:27:19 +0100
ci: lock Ubuntu runner to ubuntu-22.04 in Backport workflow
Fixes: 1aa931f6f1eb ("ci: lock workflow dependencies to increase reproducibility")
.github/workflows/backport.yml | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
commit 8be9e8ad9a238ce11fc3a1a00d4baffa4eb9ed28
Date:   2025-01-06 23:28:34 +0100
ci: update Ubuntu runner to ubuntu-24.04 in Backport workflow
Fixes: fe72c2306f51 ("ci: update Ubuntu runner to ubuntu-24.04")
.github/workflows/backport.yml | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
```
---
The following merge commit message could be used:
```
ci: lock and …
```
=> ci: lock and update Ubuntu runner in Backport workflow

modules/zed/hm.nix
This converts font sizes from pt to px for zed, using the same method from the VS Code module: https://github.com/danth/stylix/blob/168306ce7f5d823ccee8b7d4e112ea20671c2b8f/modules/vscode/hm.nix
Without this, font sizes on zed will look unexpectedly tiny.
=> zed: convert font sizes from pt to px

docs/src/commit_convention.md, docs/src/development_environment.md
The style of these two were inconsistent with the rest of the documentation corpus.
=> doc: fix two titles not using sentence case

modules/zathura/hm.nix
Since `zathura` supports opacity, I think it will be nice if `stylix.opacity.applications` option can also control that.
=> zathura: background opacity support

flake.nix
```
commit e88850f9c27bd61a0452921e9c30210ee1a1ef06
Date:   2025-01-06 17:41:13 +0100
stylix: add progress bar to nix-flake-check package
flake.nix | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
commit 0969c2e792c942dc95d98381fa389340bbff10bb
Date:   2025-01-06 17:58:23 +0100
stylix: colorize and prefix nix-flake-check output
flake.nix | 10 +++++++---
1 file changed, 7 insertions(+), 3 deletions(-)
commit 0365d80e2d3348bb8ad60dd0ef07474592387265
Date:   2025-01-06 18:13:21 +0100
stylix: decrease verbosity level of nix-flake-check package
Decrease the verbosity level of the nix-flake-check package, aligning
with …
```
=> stylix: enhance nix-flake-check output and make location-independent

flake.lock, flake.nix
```
Update all flake inputs and resolve the following warning:
warning: input 'git-hooks' has an override for a non-existent input
'nixpkgs-stable'
```
=> stylix: update all flake inputs

modules/wpaperd/hm.nix
Previously, the `fill` image scaling mode would use `fit` in wpaperd, which scales the image to fit within the screen without cropping it. This PR uses wpaperd's `center` mode instead which is closer to swaybg's `fill` mode (scales the image to fill the screen, potentially cropping).
See https://github.com/danyspin97/wpaperd#wallpaper-configuration
=> wpaperd: fix image scaling modes

modules/cavalier/hm.nix, modules/cavalier/testbed.nix
Adds a module for the new Cavalier target, a GUI for the popular Cava audio visualizer. Adds a testbed as well. I'm not quite sure what color to use as the foreground color, because the style guide doesn't cover graphs. It currently uses `base05` because that's used for text, but `base0D` would also be a desirable option.
<details>
<summary>Preview Cavalier with Catppuccin theme</summary>
</details>
=> cavalier: add module

flake.nix
`jq` is required a couple of lines below. Without it I could not run e.g. `nix run .#nix-flake-check`.
=> stylix: add jq to runtimeInputs

modules/firefox/hm.nix
Adds support for Floorp by adding it to the list of supported Firefox derivations. See https://github.com/danth/stylix/pull/695#issuecomment-2603122055.
=> firefox: support floorp browser

modules/gnome/colors.mustache
=> gnome: fix foreground color of transparent panels

.github/workflows/check.yml
```
ci: run CI on PRs and limit push event to protected branches (#751)
Run the CI on PRs, while preventing it from running twice for non-fork
PRs by limiting the push event to protected branches. [1]
This restores the workflow trigger that was accidentally modified in
commit 2b85a562355c ("ci: simplify workflows").
[1]: https://github.com/danth/stylix/pull/749#issuecomment-2573437938
(cherry picked from commit 284c5b03578eecbf3c680392ea7d0506834adc6b)
```
=> [release-24.11] ci: run CI on PRs and limit push event to protected branches

flake.lock, modules/ghostty/hm.nix, modules/ghostty/testbed.nix
```
commit fdcfef92b19743bfd3fbaee74d70b008df296c93
Date:   2025-01-24 00:25:45 +0100
stylix: update nixpkgs and home-manager inputs
commit 4f412c33ffdd5f8b0a8f3be75a7fd79e36b62cbe
Author: Mirza Arnaut <mirza.arnaut45@gmail.com>
Date:   2025-01-02 20:01:16 +0100
ghostty: init (#703)
Link: https://github.com/danth/stylix/pull/703
Reviewed-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
(cherry picked from commit 6eb0597e345a7f4a16f7d7b14154fc151790b419)
```
=> [release-24.11] ghostty: init

modules/regreet/nixos.nix, modules/wpaperd/hm.nix
```
commit 9a17eeedfdaba8d0256f710b6c4810d5f50abecc
Date:   2025-01-23 23:30:00 +0100
regreet: simplify warnings pattern using lib.optional
commit d1beabbdc5f352483141ee89e642337245d2aafb
Date:   2025-01-23 23:38:35 +0100
treewide: standardize message convention
```
=> treewide: simplify and standardize message convention

.github/workflows/check.yml, .github/workflows/docs.yml
Due to the large number of derivations we are building, this almost always gets disabled due to rate limits before it's able to fetch anything which isn't already on [cache.nixos.org](https://cache.nixos.org). Rate limiting also spams the log with warnings which are unrelated to the build.
=> ci: remove Magic Nix Cache

modules/vesktop/hm.nix
I made a change allowing stylix.theme.css to work on darwin because it wasn't working for me
=> vesktop: change theme location on nix-darwin

modules/ghostty/hm.nix
This uses the same color mapping as alacritty, wezterm, and kitty.
Also, these colors are consistent with the documentation of `mkschemeattrs` and `base16-shell`.
Context:
* https://github.com/chriskempson/base16-shell
* modules/alacritty/hm.nix
* modules/wezterm/hm.nix
* https://github.com/tinted-theming/tinted-kitty/blob/main/templates/base16.mustache
* https://github.com/SenchoPens/base16.nix/blob/main/DOCUMENTATION.md#mkschemeattrs
=> ghostty: be consistent with other terminals

docs/src/tricks.md
The tinted-theming repository has updated its scheme for themes such that colors are located under the key `palette` [1]  and such that each color is # prefixed [2]. These changes update the documentation to reflect this new schema. 
[1] https://github.com/tinted-theming/schemes/commit/4caed9a8f5ec9532c28d43c511fb7799342c6271
[2] https://github.com/tinted-theming/schemes/commit/61058a8d2e2bd4482b53d57a68feb56cdb991f0b
=> doc: Update tricks per tinted-theming schema changes

modules/waybar/hm.nix
Gives users the ability to use their own css without having to manually add stylix color/fonts. Also adds `cfg` var and reformats using `nixfmt-rfc-style`. Still not 100% sure on the naming/description. 
resolves #429, related #481
=> waybar: addCss option

flake.lock, flake.nix
Closes: https://github.com/danth/stylix/issues/800
Fixes: a88c4d264a43 ("stylix: update all flake inputs (#774)")
---
Cc: @Limvot, @alex-massa
=> stylix: downgrade and lock base16-vim input

modules/kde/hm.nix
Hi.
Fixing Plasma activation in #708 worked bit too well. Every time the theme is applied, it resets all custom theming options. I noticed this with decorations, so I added a new option to override `org.kde.breeze` with custom string.
I also took the liberty of refactoring the module a bit. To improve module maintenance, I mainly reduced the scope of `with` expressions and improve color handling.
=> kde: enable custom decorations and polish code

modules/nixcord/hm.nix
```
Closes: https://github.com/danth/stylix/issues/802
Fixes: e594886eb095 ("nixcord: init (#767)")
Link: https://github.com/danth/stylix/pull/822
Co-authored-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
Reviewed-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
```
---
Cc: @ari-rs
Supersedes: https://github.com/danth/stylix/pull/821
=> nixcord: theme Vencord and Vesktop instead of just Vencord

modules/qt/hm.nix
=> fix: fix qt6ct config folder name

modules/kde/hm.nix
```
Fixes: d9df2b4200ba ("kde: add decorations option and polish code (#772)")
```
=> kde: correct quotes in stylix-activate-kde to prevent failure

flake.lock, modules/wayfire/hm.nix
Wayfire is a 3D Wayland compositor, inspired by Compiz and based on wlroots.
Sadly, we cannot use `stylix.image`. Wayfire currently isnt smart enough to understand what file type an image has if it doesnt have a file ending and we cannot depend on that being set.
=> wayfire: init

modules/kde/hm.nix
Hello.
I went ahead and fixed #809. While at it, I also made the wallpaper image optional, correcting for some incorrect settings in Look and Feel, which will clash with #717 (but should be more correct).
=> kde(fix): make wallpaper optional and nondestructive

modules/vencord/hm.nix, modules/vesktop/hm.nix
Closes: #829 
applies Vesktop and Vencord fonts.
unsure of general best practices, will revise approach upon request
=> {vesktop, vencord}: fonts

modules/vencord/hm.nix, modules/vesktop/hm.nix
This introduced IFD and broke evaluation for flakes users.
This reverts commit be606eaa87dfcf22c98f80453b42ec40dcbcdf36 / #840
=> Revert "{vencord,vesktop}: fonts (#840)"

modules/kde/hm.nix
This PR makes a trivial change of adding a single field to `kdeglobals`, as proposed in #833. I added the field directly to the theme files, but it is possible to add it as user config if this decides not to work. While it did work for me, I explicitly disabled the new `qt` module, because it broke my DE, so I don't know how those two interact. @FirelightFlagboy could you please test this please?
=> kde: fix KDE apps ignoring colorscheme

.github/workflows/check.yml, flake.lock, flake.nix, stylix/testbed.nix
Avoid incidents like #840/#844 by explicitly blocking IFD in our CI's `nix.conf`.
I checked that this works by cherry-picking this commit onto 7818098, before we reverted be606ea, and verifying that the build failed.
=> ci: block IFD

modules/gnome/hm.nix, modules/kde/hm.nix
This suffers from the same issues as the KDE activation:
- The program is not available in `$PATH`, but should not be installed for all users
- The program only works when GNOME Shell is running
Therefore, we use a very similar solution.
=> gnome: fix Home Manager activation

modules/gnome/hm.nix, modules/kde/hm.nix
=> [release-24.11] gnome: fix Home Manager activation

flake.lock
```
Closes: https://github.com/danth/stylix/issues/870
Link: https://github.com/danth/stylix/pull/871
Reviewed-by: NAHO <90870942+trueNAHO@users.noreply.github.com>
(cherry picked from commit 21d68dab9dff35d88125f9ddd7d11477a628d071)
```
=> [release-24.11] firefox: update GNOME theme input (#871)

modules/qt/nixos.nix
This adds temporary warnings when plasma6 is enabled and will be
replaced with actual handling of plasma6 when styling solutions are
added upstream.
Currently, this requires a manual work around that is only reasonable on
home-manager and not on NixOS. Users will be deferred to find
workarounds in the issue when they encounter this warning.
Relates to #835
=> qt: add temporary warnings for plasma6

docs/book.toml
Since the documentation is now hosted at https://stylix.danth.me/ rather than https://danth.github.io/stylix/, this setting is no longer necessary.
=> doc: remove `site-url`

modules/swaylock/hm.nix
The swaylock Home Manager module automatically enables itself when `settings != {}` and the state version is earlier than `23.05`:
https://github.com/nix-community/home-manager/blob/5cfbf5cc37a3bd1da07ae84eea1b828909c4456b/modules/programs/swaylock.nix#L12-L17
This corrects the Stylix module to avoid providing settings unless the user already has swaylock enabled, so that swaylock is not installed for all Stylix users.
Fixes #843
=> swaylock: avoid inadvertently installing swaylock

flake.lock, flake.nix, modules/firefox/hm.nix, stylix/templates.nix
Adds the `colorTheme.enable` option to firefox derivatives. This installs and configures the Firefox Color extension.
This is not enabled by default because writing extension settings requires manually setting `extensions.force = true`. See https://github.com/nix-community/home-manager/pull/6490.
This doesn't conflict with the `firefoxGnomeTheme.enable` option. It even enhances it, because it sets a newtab background color, which the gnome theme doesn't.
=> firefox: add color theme

.github/workflows/check.yml
```
Make the get-derivations job fail when the command writting to the
$GITHUB_OUTPUT file fails.
Previously, the $GITHUB_OUTPUT file was successfully created when the
input command failed, resulting in an empty $GITHUB_OUTPUT file. [1]
[1]: https://stackoverflow.com/questions/59287865
```
=> ci: make get-derivations job fail when input command fails

README.md
It now only includes one testbed, as listing all possible combinations is unnecessary for a basic demonstration.
Follows #717
=> doc: update GNOME testbed name in README

.github/workflows/check.yml, .github/workflows/docs.yml
I tested the required amount of space by building a `pkgs.linkFarm` containing all testbeds, then manually pushing this to an empty Cachix cache.
The total storage used has not yet updated in the UI, and I'll add the exact measurement here when it does. However, I'm fairly sure that the used space is far less than what is available on the free plan.
Fixes #880
=> ci: add Cachix cache

docs/src/configuration.md, modules/nixvim/nixvim.nix
Allow standalone nixvim users to take advantage of stylix by exposing the generated config as `config.stylix.targets.nixvim.config`.\
I'm open to other names; maybe `out`, `build`, `cfg`, `module`?
This can be passed to the nixvim derivation's `extendNixvim` function, as described in the option description.
Ideally, this would be documented outside of the home-manager/nixos options page, but IMO this is fine. I guess _stylix_ would still be installed via nixos/hm/etc even if nixvim was a standalone build...
I also considered detecting the environment the option is being used in and producing a more specific example; i.e. use `home.packages` in the home-manager docs' example. I figured this was overkill, and the example should be clear enough for anyone choosing to use standalone nixvim. …
=> nixvim: expose config for nixvim's standalone mode

modules/qt/kvantum-svg.mustache, modules/qt/kvconfig.mustache
The Kvantum theme is based on the Catppuccin Kvantum theme[^1]. However, this is partially incompatible with the Stylix styling guide[^2]. This caused issues like unreadable buttons and other inconsistencies. This commit aims to fix this issue.
<details>
<summary>Preview UI changes</summary>
</details>
[^1]: https://github.com/danth/stylix/pull/142#issue-1837991495
[^2]: https://stylix.danth.me/styling.html
=> qt: adapt to style guide

.github/workflows/check.yml, .github/workflows/docs.yml
This commit allows CI jobs to degrade gracefully if Cachix has issues, by skipping uploads and/or building packages from scratch rather than failing the job.
This is in response to the recent failures on `master`, which appear to be caused by a 502 (Bad Gateway) response while uploading some of the build results.
=> ci: ignore Cachix errors

modules/rio/hm.nix
https://rioterm.com/docs/config#fontsemojis
fixes #936
=> rio: add emoji font family; use correct font size units

.editorconfig
> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.
Based on hm and nixpkgs editorconfig. Not sure about how many spaces to indent css and html/xml/svg files (it's not consistent in the codebase). A future pr should probably standardize the mustache file extensions (so all css files are `.css.mustache` for example).
=> stylix: add editorconfig

stylix/palette.nix
Replaces #912
I messed up my git. Really sorry for that.
=> palette: fix eval fail when image is null

README.md, flake.nix
```
commit f6135feb96da3ab84192312831eca1dbaf24ed00
[...]
stylix: add flake description
commit d7033fc12eef3bd0f09b87742bf78c3cd53c1197
[...]
doc: make project synopsis more concise
```
---
Upon merging this PR, the GitHub project description should also be updated:
=> doc: add flake description and overhaul README

modules/vim/hm.nix
Hi, 
following #926, this fix:
```nix
error: attribute 'input' missing
at /nix/store/6ji5yp49qfmk71rwr1yhgwl91nbgcqyx-source/modules/vim/hm.nix:10:20:
9|   themeFile = config.lib.stylix.colors {
10|     templateRepo = config.lib.stylix.input.base16-vim;
|                    ^
11|     target = "base16";
=> vim: fix incorrect input path

modules/waybar/hm.nix
fixes #956
also moves `with` to scope they are used in
=> waybar: add font option; default to monospace

modules/firefox/hm.nix
warns users when they have a firefox-like program enabled but stylix has no profiles to theme
aligns behavior with #914
=> {firefox, librewolf, floorp}: add profile warning

flake.nix
```
Fixes: e3233ead63f5 ("stylix: init droid (#778)")
```
=> stylix: add missing comma in flake description

modules/glance/hm.nix
The original conversion function has two issue
1) the saturation value should be in [percentage not in decimal](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#theme)
2) the hue value is limited to integer multiple of 60 as the calculation only use integer 
- e.g. RGB(36, 39, 58) will give out HSL(240, 0, 18) instead of HSL(231, 23, 18) 
Code changes:
- to fix 1), s is multipled by 100
- to fix 2), the calculation is done in floating point and convert back to int
- the phase wrapping is done manually as `mod` doesnt support float point
- nix don't have `round`, `floor` is used instead
=> glance: fix rgb-to-hsl conversion

modules/vscode/testbeds/default.nix
Previously, the theme was not enabled in the testbed because there were no existing profiles.
=> vscode: set profile name in testbed

docs/default.nix, docs/src/SUMMARY.md
Fixes #896, and unblocks #947, by creating a custom implementation of `pkgs.nixosOptionsDoc` where we only need to evaluate each platform configuration once.
Additionally, changes the display of option details to use tables, since we now have the flexibility to do this.
<details>
<summary>Old</summary>
</details>
<details>
<summary>New</summary>
</details>
=> doc: implement custom option list generation

stylix/home-manager-integration.nix
Minor change to fix an error raised on Darwin. The cursor attribute was undefined, I think after #943 was merged. Addresses #1003
=> stylix: fix cursor undefined error on darwin

modules/firefox/hm.nix
- Made the descriptions of `colorTheme.enable` and `firefoxGnomeTheme.enable` specify which Firefox derivative they apply to, to clarify that these options are specific to each derivative.
- Switched from `mkEnableTarget` to `mkEnableOption`, as these options are not strictly targets: they enable additional programs. This also changes the option description slightly.
- Removed the multi-line string as this was adding whitespace where it's not needed, due to the trailing newline.
=> firefox: improve option descriptions for extensions

modules/mpv/hm.nix
This change sets the mpv background color to black.
In the original implementation, the letter-boxing black bars would instead be a different color, determined by the theme.
Before:
After:
=> mpv: set background to black

docs/src/modules.md
Fixes: e43eb4e2a7df ("stylix: init module maintainers framework (#977)")
=> doc: format Nix code in Maintainers section according to our formatter

modules/k9s/hm.nix, modules/k9s/meta.nix
I found that there were some color choices in the k9s module that
weren't aligned with the style guide. Most notably this resulted in
healthy resources being displayed in red while unhealthy resources were
blue.
I tried not to make any subjective changes to the original module
because overall, it was very well done, and there's no right answer when
it comes to things aren't covered by the style guide. In some cases
where the style guide doesn't help, I looked at other modules for
answers.
These are the changes, and the reason for them.
1. prompt.bgColor from base00 to "default" for transparency to shell
background.
2. prompt.suggestColor from base0A to base02 because base02 is used as
fish_color_autosuggestion in base16-fish via the fish module.
3. dialog.bgColor from "default" to base01 …
=> k9s: tweak color assignment to style guide

docs/default.nix
This avoids the metadata looking like part of a README subheading:
---
---
=> doc: add subheading before module metadata

docs/default.nix, docs/src/configuration.md, modules/discord/README.md, modules/nixvim/README.md, modules/nvf/README.md, modules/spicetify/README.md
Using too many "info" and "warning" boxes makes them less effective when they're needed to draw attention to something genuinely important.
This pull request adds important boxes around the information added in #1039 - similar to the box already used on the "Firefox and derivatives" page.
It removes the warning when a module has no maintainers, which is now a regular paragraph. Furthermore, the note about `stylix.enable` being new is removed since this has been around for a while now.
=> doc: reduce overuse of alerts

modules/vscode/hm.nix, modules/vscode/testbeds/default.nix
adds "default" to profiles because this is the profile that VSCode uses upon opening in a novel folder.
removes unnecessary `profileNames` declaration from the testbed
i think that the warning can stay as it would be better that the user disable the target through the enable option rather than setting `profileNames` to `[ ]`.
=> vscode: theme default profile by default

.github/ISSUE_TEMPLATE/config.yml
This directs questions to either Discussions or the Matrix room.
I strategically chose names starting with "A" in the hope that these will be alphabetically sorted to the top of the list.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
=> doc: add contact links to issue template chooser

.github/workflows/check.yml, docs/src/development_environment.md, flake.nix
This works around GitHub's limit on the number of matrix jobs (fixes #947), by running all builds in a single job. To maintain some speed, we use [`nix-fast-build`](https://github.com/Mic92/nix-fast-build#readme), which uses multiple cores for evaluation, and skips any builds for which the final derivation is already in a binary cache.
Although this makes the run for an individual pull request slower, the amount of duplicated work is greatly reduced: previously, we often had 100 machines building the same derivation in parallel. This means that more runners are available should there be multiple pull requests opened in a short space of time, so there is less queuing. It's also more energy efficient :leaves:
A potential downside is that the logs are all merged together, so it can be hard …
=> ci: run all builds in a single job

flake.lock, modules/emacs/meta.nix
Aswering the call of the Council. ;-)
Note that my handle has been added to nixpkgs’ `/maintainers/maintainers-list.txt` but [a few minutes ago](https://github.com/NixOS/nixpkgs/pull/393504).
Thanks for the opportunity!
=> emacs: add panchoh as maintainer

modules/bat/base16-stylix.tmTheme.mustache
See #1034. As mentioned there, it may be more appropriate to change this to a URL-reference if the template has not been modified from the original.
@dwarfmaster, if you're still active, as you added this in #68, can you confirm I got the right source for the template? This is the only link I found when searching for "bat base16".
=> bat: add copyright notice

stylix/cursor.nix
changes:
- alters `stylix.cursor` option description
- adds `null` defaults to each of the options under `stylix.cursor`
- adds check that either all or none of `stylix.cursor` is set
related: #1064
=> stylix: document cursor option coreliance

modules/wayfire/hm.nix
It seems the recent effort to make `stylix.image` optional has broken the wayfire module. This PR solves the issue, and allows it to evaluate again
Pinging... myself?
=> wayfire: fix broken wallpaper option

docs/src/modules.md, modules/gnome-text-editor/overlay.nix, modules/nixos-icons/overlay.nix, stylix/overlays.nix, stylix/target.nix
this should stop the warning from appearing
previously when overlays where disabled they where set to
```nix
[
(_: _: { })
(_: _: { })
]
```
Now setting `nixpkgs.overlays` is behind a mkIf
resolves #865
=> stylix: ensure overlays aren't set when disabled

modules/swaylock/hm.nix
The colours selected for swaylock did not seem to match the style guide's recommendations, leading to low contrast between the green arc on the ring and the background of the ring. The colours have been updated to follow the style guide.
<details>
<summary>
Images
</summary>
</details>
Closes: #1047
=> swaylock: fix colors to better align with the style guide

.github/workflows/backport.yml, .github/workflows/update-flake.yml
@danth you should be able to set it up with [this guide](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow)
supersedes #520
=> ci: add flake update action

modules/bspwm/testbeds/default.nix
changes:
- adds bspwm testbed
- based on hyprland testbed
- launches kitty on startup for viewing window borders
- does not configure keyboard shortcuts
related: #319
=> bspwm: add testbed

.github/workflows/update-flake.yml
As far as I can tell, this workflow doesn't use the cache at all.
=> ci: skip adding Cachix for flake updates

docs/src/modules.md, modules/kde/hm.nix
changes:
- adds `run` wrapper to `home.activation` script
- from a very surface-level visual analysis, this does not seem to change anything about the module's function
- adds a `Common Mistakes` section to the modules page
fixes: #313
=> kde: add run wrapper

modules/plymouth/theme-script.nix
The passed in prompt can wary, e.g. with a
FIDO key (Yubikey) used for LUKS decryption
@0x5a4
=> Plymouth: don't use static prompt

modules/qt/nixos.nix
Fixes #835
Now that kde6 is in both upstream nixpkgs and home-manager we can use that when theming plasma6.
This seems to bring plasma 6 from non-functional to functional with styling despite not changing the hm code (or warning).
=> qt: fix kvantum breaking plasma6

flake.lock, modules/helix/hm.nix
Supersedes https://github.com/danth/stylix/pull/1125 because I am unable to `git push --force-with-lease` the resolved `git rebase master` merge conflicts to the PR's branch. This is merely an intermediate PR to avoid directly pushing to master.
=> helix: use theme option

flake.lock, modules/zed/hm.nix
option added by https://github.com/nix-community/home-manager/pull/6832
=> zed: use theme option

stylix/palette.nix
```
Apply the standardized message convention, introduced in commit
5e8be7521e8f ("treewide: simplify and standardize message convention
(#796)").
Fixes: c8e4a0d2186d ("treewide: optionalize stylix.image option (#717)")
```
=> stylix: apply standardized message convention

flake.lock, flake.nix, modules/foot/hm.nix
**:warning: We should get this merged asap (with proper reviews ofc) b/c master is very broken right now :warning:**
I forked base16 to make the `$out` of the mk-theme be a file instead of a dir with one file, so that `lib.isStorePath` returns true ([commit](https://github.com/awwpotato/base16.nix/commit/985d704b4ff9f75627f279ef091b2899f8456690)).
fixes #1161 
fixes #1163
necessary for #1158
=> stylix: use awwpotato's base16.nix fork

modules/fcitx5/hm.nix, modules/firefox/hm.nix, modules/gedit/hm.nix, modules/gnome-text-editor/overlay.nix, modules/gnome/theme.nix, modules/gtk/hm.nix, modules/qt/hm.nix
This fixes the issue mentioned at https://github.com/danth/stylix/pull/1164#pullrequestreview-2789195255
=> treewide: add missing `.`s to extensions

flake.lock, modules/discord/hm.nix, modules/discord/testbeds/vesktop.nix
- Uses `programs.vesktop.vencord.themes` option introduced by https://github.com/nix-community/home-manager/pull/6860
- Automatically enables theme
- Removes `extraCss` option
=> vesktop: use upstream options

modules/alacritty/testbeds/default.nix, modules/cavalier/testbeds/default.nix, modules/chromium/testbeds/default.nix, modules/discord/testbeds/vencord.nix, modules/discord/testbeds/vesktop.nix, modules/emacs/testbeds/default.nix, modules/firefox/testbeds/default.nix, modules/firefox/testbeds/gnome-theme.nix, modules/foot/testbeds/default.nix, modules/gedit/testbeds/default.nix, modules/ghostty/testbeds/default.nix, modules/glance/testbeds/default.nix, modules/gnome-text-editor/testbeds/default.nix, modules/halloy/testbeds/default.nix, modules/kitty/testbeds/default.nix, modules/mpv/testbeds/default.nix, modules/mpv/testbeds/modernz.nix, modules/mpv/testbeds/uosc.nix, modules/qutebrowser/testbeds/default.nix, modules/vscode/testbeds/default.nix, modules/wezterm/testbeds/default.nix, modules/yazi/testbeds/default.nix, modules/zathura/testbeds/default.nix, stylix/testbed.nix
changes:
- removes `stylix.testbed.application.enable` option
- it is now assumed that, if the option is set, the application should be run
- removes repeated lines
- moves `stylix.testbed.application` to `stylix.testbed.ui.application`
- if any options are set under `stylix.testbed.ui`, the UI configuration is set
- refactors all existing application testbeds reflect the above two changes
- adds `stylix.testbed.ui.command.{text,useTerminal}`
- if the option is set, the command should be run
- functions similarly to `stylix.testbed.ui.application` except can take any arbitrary command
- has an option to run the command in a terminal
- useful for terminal applications which require a terminal emulator for their full functionality
related: #319
=> treewide: add testbed option for running command in UI

modules/wofi/testbeds/default.nix
Wofi does no provide a desktop file, so I had to create one to be ran on the testbed.
Maybe there could be an option to run a command as auto-start inside the DE?
=> wofi: add testbed

modules/neovim/hm.nix, modules/nixvim/nixvim.nix
very small addition, but it's easier than adding the highlight override in nixvim directly.
Probably could also use a transparent global enable option that all the transparentbackground.* use as default value?
=> nixvim: transparency option for numberLine

modules/mpv/hm.nix
Set more sensible default values for mpv:
- Sans serif for UI and subtitle font, instead of monospace, just like other graphical programs.
- Dim background video using `base00` instead of a blaring blue.
- Red for error, instead of brown
- Green for success, instead of yellow
I used the mnemonics instead of the `baseXX` format for the chroma colors, if that's okay.
=> mpv: more sensible values

stylix/testbed.nix
This allows testbed autostart to be more complex than a single command.
See #1191.
@awwpotato, @Flameopathic What do you think?
=> testbed: wrap autostart command in a shell script

modules/mpv/hm.nix
Unsets the curtain color for dimming in uosc, so that it falls back to the default. Dimming color should be decoupled from the user's theme:
> > > Dim background video using `base00` instead of a blaring blue.
> > 
> > 
> > If this is for dimming then it might be better to use a hardcoded black - with a light theme using `base00` will make the video brighter.
> 
> actually unsetting it would make more sense if we don't want it to be related to the color scheme
=> mpv: unset custom curtain color for dimming

docs/src/configuration.md, modules/nixvim/README.md
At the time the standalone-mode docs were added, per-module READMEs did not exist (or I didn't know about them).
Follow up to #415
@trueNAHO
=> nixvim: move standalone-mode docs from configuration → nixvim readme

docs/default.nix
Markdown uses ```` ``` ```` to start and end fenced code blocks. However code blocks can themselves contain ```` ``` ```` sequences.
To deal with this, markdown allows code block fences to be of arbitrary length; any sequence of fence-chars that is shorter than the opening fence will not terminate the code block.
We can scan through the code block text to find the longest sequence of `` ` ``-chars to ensure the opening/closing fences are longer than the longest in the code block.
In practice, it is rare for code blocks to contain fences, but it is more robust to check for them.
=> doc: ensure code blocks are safely fenced

docs/default.nix
- **Revert doc: use lib.max**
- **doc: add clarifying comments to `longestFence`**
Reverts deda0145c267e1a6d785aed27ad2a024693f0545 from #1218
=> doc: fix `longestFence` usage of `lib.max`

modules/sxiv/testbeds/default.nix
I had to force-load Xresources. I'm not sure why it's not loaded by default on gnome...
=> sxiv: add testbed

flake.lock
Bump base16.nix to include a color mnemonic fix: 
- https://github.com/SenchoPens/base16.nix/pull/25
=> stylix: bump base16.nix flake

stylix/fonts.nix
Derivation values shouldn't be rendered in option docs. Instead a `literalExpression` or `literalMD` should describe the default/example.
This PR was cherry-picked from #1212 in an effort to make that PR smaller and easier to review, while also making _these_ changes easier to focus on in a dedicated PR.
---
I've gone a step further than the minimal fix originally proposed in #1212, as I believe the options can be simplified a little:
1. I'm not convinced each font option needs to be a submodule
- they could just be a set of nested options
- submodules are more useful when there is compartmentalised logic or reusable types
2. I'm not convinced the defaults are best defined/documented at the top-level font option instead of at the sub-options (`name` and `package`)
3. Pushing down the …
=> stylix: simplify font options & use `literalExpression` default packages

flake.nix, modules/fnott/hm.nix, modules/fnott/meta.nix
- **fnott: add MrSom3body as maintainer**
- **fnott: set font size**
See commit messages
(created a separate pr from #1223, so this change can be merged)
@awwpotato
=> fnott: set font size

modules/yazi/hm.nix
Selection background color should be `base02` by convention: https://github.com/tinted-theming/base24/blob/main/styling.md.
I also changed `find_position` to magenta from a plain white, because I think it looks a bit nicer that way.
=> yazi: tweak colors

flake.lock, modules/starship/hm.nix
- Bump `base16.nix` to include a color mnemonic fix
- https://github.com/SenchoPens/base16.nix/pull/25
- Remove non-existent `bright-orange` color in `starship`
- Make black and white colors in `starship` conform to `base24` specification
- https://github.com/tinted-theming/base24/blob/main/styling.md#specific-colours-and-their-usages
=> stylix: update base16

flake.nix, stylix/check-maintainers-sorted.nix
cherry picked from https://github.com/danth/stylix/pull/1208
=> stylix: use call package for check-maintainers-sorted

modules/foliate/hm.nix, modules/foliate/meta.nix, modules/foliate/testbeds/default.nix, stylix/maintainers.nix
The [Foliate](https://johnfactotum.github.io/foliate/) application's main UI is themed with GTK, but the actual Ebook reader is not. This module generates a `stylix.json` file in the Foliate configuration directory, and then uses dconf settings to select it as the theme. I've been using this theme locally for a while with raw JSON, but I translated it to nix to keep things pure, and then tested the whole thing in a testbed.
Pretty much the only options available are the `fg`, `bg`, and `link` colors, which are showcased here. I just inverted the `fg` and `bg` for light/dark.
Added myself as maintainer
=> foliate: init

modules/kde/testbeds/default.nix, modules/kde/testbeds/plasma5.nix
Adds testbed for plasma6.
In NixOS 25.11 plasma5 will be deprecated so plasma6 should become the default.
Relates to #1092
=> kde: add and update testbeds

docs/src/configuration.md
=> doc: use hash instead of sha256 in example

docs/src/modules.md, modules/gtk/hm.nix, modules/kitty/hm.nix, modules/kubecolor/hm.nix, stylix/target.nix
> [!NOTE]
> This PR is comprised of intentionally separate commits, please don't squash :slightly_smiling_face:
The global `stylix.enable` option is not relevant to the per-target `enable` option's default. Instead it should be checked in addition to the per-target `enable` option so that is is effective even when a target is explicitly enabled.
Since the target module has to check the global enable separately from the per-target enable, including it in the per-target option's value has no effect.
I spotted this while working on #1244. It felt odd that enable options had a seemingly redundant default: `stylix.enable && stylix.autoEnable`.
See also: https://github.com/danth/stylix/issues/543
Closes: https://github.com/danth/stylix/pull/419
To give a concrete example of where this default …
=> stylix: `mkEnableTarget` should not check `stylix.enable`

docs/default.nix, docs/src/installation.md, flake.nix
see https://github.com/nix-community/home-manager/pull/6406
cherry picked from https://github.com/danth/stylix/pull/1208
cc @MattSturgeon
=> stylix: rename homeManagerModules to homeModules

modules/cava/hm.nix
the current description is "Whether to enable theming for rainbow gradient theming," which is  obviously incorrect.
=> cava: refactor + fix rainbow.enable description

flake/default.nix, flake/deprecated.nix, flake/modules.nix
Three issues:
1. Need to move the `mkIf` up to the `flake` definition, doing it within `flake` will lead to an empty value stub due to [`lazyAttrsOf`](https://nixos.org/manual/nixos/unstable/#sec-option-types-composed).
2. The version should be `2605` not `2511`
3. The check should be inverted
Rather than having a `flake = mkMerge` in `flake/outputs.nix`, I've added another module `flake/deprecated.nix`.
=> flake: fix and refactor the `homeManagerModules` alias

flake/packages.nix
```
Include the packages in the checks output to resolve the regression
introduced in commit 8b015b5fa0d7 ("flake: use flake-parts (#1208)").
Fixes: 8b015b5fa0d7 ("flake: use flake-parts (#1208)")
Link: https://github.com/danth/stylix/pull/1285
```
Packages were accidentally removed from checks in #1208
@trueNAHO @MattSturgeon
=> flake: include packages in checks

modules/gnome-text-editor/overlay.nix
fixes #1294.
[this upstream commit](https://gitlab.gnome.org/GNOME/gnome-text-editor/-/commit/5ad4beb8ebb58ebc57e73c4ac010b6cf790947ea) removes share/gnome-text-editor/styles directory breaking the overlay.
I've briefly tested locally on gnome-48 and using the testbed on gnome-47.
Alternatively #958 should fix this once merged.
=> gnome-text-editor: update style path

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/change_option.yml, .github/ISSUE_TEMPLATE/change_target.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/new_option.yml, .github/ISSUE_TEMPLATE/new_target.yml, .github/workflows/backport.yml, .github/workflows/labels.yml, .github/workflows/update-flake.yml, README.md, docs/book.toml, docs/default.nix, docs/src/installation.md, docs/src/modules.md, docs/src/testbeds.md, flake.nix, modules/kde/hm.nix, modules/mangohud/hm.nix, modules/micro/hm.nix, modules/qt/hm.nix, modules/qutebrowser/hm.nix, modules/xfce/hm.nix
Preparing to migrate the repository into https://github.com/nix-community. The most important change here is in the Actions workflows, as they check the owner's name to decide whether to run.
The documentation is still at https://stylix.danth.me for the time being.
=> treewide: change repository owner to nix-community

flake.lock, flake.nix, modules/gnome/colors.scss.mustache
Fixes #1293.
~~Note that there are problems in the testbed in the published version of this PR, since updating our Nixpkgs input to have the new GNOME version would trigger #1294 and cause the checks on this PR to fail. However, I tested this locally with the input updated and the `gnome-text-editor` target disabled.~~
=> gnome: update CSS to version 48.1

docs/src/modules.md
By leveraging nix’ `--override-input` parameter, we spare the user from having to run `nix flake lock --update-input stylix` after every edit of their local Stylix fork.
“But, `nix-on-droid` does not support that flag!”, you might say.
Well, now it [does](https://github.com/nix-community/nix-on-droid/pull/457), muahaha!
EDIT: the following table was going to be part of the PR, but was ultimately discarded. I’ll leave it here to support the changes to the docs.
- On NixOS
```console
```
- or, equivalently
```console
$ nix build .#nixosConfigurations.«hostname».config.system.build.toplevel --override-input stylix git+file:/home/user/path/to/stylix
```
- On Nix-Darwin
```console
$ nix build .#darwinConfigurations.«hostname».system
$ ./result/sw/bin/darwin-rebuild switch
```
- On Nix-on-Droid …
=> doc: simplify 'Development Setup' section

docs/book.toml
Documentation has moved to https://nix-community.github.io/stylix/, so this is necessary again for the 404 page to work correctly.
Reverts aeb550add3bfa1ce3ce249c3b3dad71ebb018318
Closes #1303
=> doc: set site-url

modules/gnome/hm.nix
It was always intended that Stylix would install this extension itself, as the Home Manager module's functionality relies on it.
I'm not sure whether this code has always been missing, or if it was accidentally removed at some point, as I only noticed when #1305 started happening and I went to check whether the extension was enabled.
Note that the extension is less than 100 KiB and isn't executed unless GNOME is running (it's not on `$PATH` or anything), so although installing this for all users is not ideal, it shouldn't cause any major problems.
=> gnome: install User Themes extension

README.md
link was still pointing at old documentation
Fixed dead link in README
@danth
=> stylix: fix link to docs in README

flake.lock, flake.nix, modules/kitty/hm.nix
It's archived now so why not use the latest commit?
Updating to the latest and final commit of [github:tinted-theming/tinted-kitty](https://github.com/tinted-theming/tinted-kitty) fixes color inconsistency, where bright tones of primary colors were assigned arbitrary colors of the selected theme (e.g. background colors in catppuccin).
@trueNAHO
=> kitty: tinted-kitty commit bump

modules/qutebrowser/hm.nix
```
Do not declare the
programs.qutebrowser.settings.webpage.preferred_color_scheme option with
lib.mkDefault to avoid accidentally overriding it [1] ("treewide:
declare options with lib.mkDefault").
[1]: https://github.com/danth/stylix/pull/388
```
=> qutebrowser: remove lib.mkDefault option declaration

.github/labeler.yml
designed to keep stable and unstable in sync, but shouldn't be in stable branch.
=> [release-25.05] ci: don't backport ci to 24.11

.github/labeler.yml, flake.lock, stylix/release.nix
fixes #1315 
related to #1277 
> [!NOTE]
> 25.05 has already been branched off so this will not end up in it.
=> stylix: bump release to 25.11

flake/packages.nix, modules/discord/testbeds/vencord.nix, stylix/testbed.nix
> [!NOTE]
> This PR includes some commits that do not make sense to be squashed, such as slightly off-topic cleanup and refactoring.
- **stylix: use `concatMapStringSep` in testbed.nix**
- **stylix: use `concatMap` in testbeds.nix**
- **stylix: refactor textbed.nix autoload**
- **stylix: add testbed enable option**
- **stylix: use a cheaper module eval for the `enable` option**
- **discord: use new enable option for testbed**
I've added a `stylix.testbed.enable` option to testbeds.
When set to false, the testbed is not included in the output of `stylix/testbed.nix`.
> ### enable
>
> Whether to enable this testbed.
>
> The testbed will not be included as a flake output if set to false;
>
> > [!CAUTION]
> >
> > This option's value can only evaluate `lib` and `pkgs` inputs,
> > if it reads …
=> stylix: improve how discord testbed is disabled

flake/packages.nix, modules/discord/testbeds/vencord.nix, stylix/testbed.nix
```
Revert the improval of how discord testbed is disabled to get the proper
commit structure into the commit history.
Reverts: 5113479d69e6 ("stylix: improve how discord testbed is disabled (#1291)")
```
=> stylix: revert improval of how discord testbed is disabled

doc/src/modules.md, modules/alacritty/hm.nix, modules/hyprland/hm.nix, stylix/autoload.nix, stylix/mk-target.nix
Changes:
- Adds `mk-target` function in accordance with #1009 
- Some alterations have been made. See updated docs.
- Uses the function for Hyprland
- Uses the function for Alacritty
=> stylix: add `mkTarget` function

modules/alacritty/hm.nix
the `with colors` got messed up, and opacity was also being applied wrong
cc @Flameopathic @MattSturgeon @trueNAHO
=> alacritty: fix mkTarget usage

.github/workflows/conflicts.yml
makes it much more obvious when a pr has a merge conflict, also used by home-manager and nixpkgs
note this is somewhat related to https://github.com/danth/stylix/pull/1256
=> ci: add workflow to label merge conflicts

modules/hyprland/hm.nix
https://github.com/nix-community/stylix/pull/1130#issuecomment-2900037709
cc @Lyndeno @Flameopathic 
entire module was previously guard by `config.wayland.windowManager.hyprland.enable`, which got lost in the switch to mkTarget
https://github.com/nix-community/stylix/blob/a2f8840bed6daade6b980426c9f72dd672e92329/modules/hyprland/hm.nix#L19
@trueNAHO @skoove
=> hyprland: fix hyprpaper enable condition

modules/foot/hm.nix, modules/foot/meta.nix
- **foot: add MrSom3body as maintainer**
- **foot: fix setting font size**
[This](89edd2f3c0b6e921aebf3ebe02fbc73a057345f5) commit broke setting the font size because of an unneeded equal sign. This fixes it and add I added myself as a maintainer.
=> foot: fix font size

modules/bemenu/hm.nix
af4f2b56 broke bemenu, with
```nix
error: undefined variable 'alternate'
at /nix/store/j55w5xjmb9i002c4hi65m555vag99g8q-source/modules/bemenu/hm.nix:66:24:
65|
66|             ab = "${if alternate then base00 else base01}"; # Alternate bg
|                        ^
67|             af = "${if alternate then base04 else base05}"; # Alternate fg
```
=> bemenu: fix undefined variable error

flake/default.nix, modules/vscode/package.json, modules/waybar/base.css
Was added in #1335 for formatting JavaScript. This PR extends it to also cover CSS and JSON.
@trueNAHO
=> flake: use biome formatter for JSON & CSS

stylix/palette.nix
The issue happens when `config.stylix.base16Scheme` is null and it is passed to `mkSchemeAttrs` to create `config.lib.stylix.colors`. This leads to an eval failure while checking assertions, meaning the assertions themselves never get printed.
Fixes #1046 and #1385
- Tested with MRE described in #1385
=> stylix: check base16Scheme is not null before using mkSchemeAttrs

stylix/palette.nix
Previously:
- Out-of-store paths were not necessarily copied to store.
- Derivations were needlessly coerced to strings.
- `package` and `path` were both used, despite `path` being a superset of `package`.
=> stylix: improve type for `stylix.image` option

.github/workflows/backport.yml
- Check APP_ID variable instead of owner
- Fix `event_name` → `event.action`
- Fix `startsWith` parameter order
See:
- https://github.com/NixOS/nixpkgs/commit/b62d9a22fbab05be9b6fdb473d89fc2fd9fe4c1d
- https://github.com/NixOS/nixpkgs/commit/01900de145ad773dc3d289cb8dcfc35b7b9c32a2
- https://github.com/NixOS/nixpkgs/commit/b6375b21c0996de13051110c80ff72ec1669261c
=> ci: fix backport conditions

modules/yazi/hm.nix
The latest release of yazi (which is already in nixos-unstable) changed the "manager" field to "mgr" (see https://github.com/sxyazi/yazi/releases/tag/v25.5.28). This fixes it so yazi stops complaining and trying to fix the read-only theme file
=> yazi: Change deprecated "manager" to new name "mgr"

stylix/mk-target.nix
imports is necessary for renamed/removed options. Note that imports is "unsafe" and might cause failure to check `!= null` (maybe a different way would be better?)
cc @trueNAHO @MattSturgeon @Flameopathic
=> stylix: add imports to mkTarget

modules/gnome-text-editor/nixos.nix, modules/gnome-text-editor/overlay.nix
=> gnome-text-editor: use mkTarget

modules/firefox/meta.nix
```
Although qutebrowser is my main browser, I occasionally use LibreWolf
and Tor Browser. Consequently, I am adding myself as a maintainer to
this rather important module.
```
=> firefox: add naho as maintainer

modules/wayprompt/hm.nix
To reduce the surprise factor when comparing it to the other color specs in this file.
See the conversation starting [here](https://github.com/nix-community/stylix/pull/1378#discussion_r2106267423).
Ref: #1378
maintainers: @nukdokplex, @panchoh
=> wayprompt: drop `-hex` suffix on single color value

doc/src/modules.md, modules/feh/hm.nix, modules/feh/nixos.nix, modules/gnome/hm.nix, modules/hyprland/hm.nix, modules/qt/hm.nix, modules/qt/nixos.nix, modules/swaylock/hm.nix, stylix/mk-target.nix, stylix/target.nix
> [!NOTE]
> This PR is comprised of intentionally separate commits, please don't squash :slightly_smiling_face:
This is a solution to the issues uncovered by #1212. This should fix #98 (not tested).
- Avoid evaluating dynamic conditions while rendering the docs.
- Define literal expressions describing dynamic conditions.
- Tested: all workarounds can be removed in [#1212](https://github.com/danth/stylix/pull/1212), when merged with this PR.
Previously, the literal markdown `` same as `stylix.autoEnable` `` was used. When an additional `conditionText` is supplied, it will now use the literal expression ``  stylix.autoEnable && ${expr} ``.
If the `expr` contains any [nix operators](https://nix.dev/manual/nix/2.28/language/operators) with a lower priority than `&&`, it will be auto-wrapped …
=> Add `mkEnableTargetWith` and use it for documenting dynamic `autoEnable` conditions

doc/src/configuration.md, modules/font-packages/meta.nix, modules/fontconfig/fontconfig.nix, modules/fontconfig/hm.nix, modules/fontconfig/meta.nix, modules/fontconfig/nixos.nix
=> fontconfig: align Home Manager with NixOS and enhance docs

modules/vscode/meta.nix
This PR simply adds a tip in the description of the VSCode documentation page, that the colors can be overridden using the [VSCode settings](https://code.visualstudio.com/docs/configure/themes#_customize-a-color-theme).
Feel free to suggest rewording or reject this PR if it feels unnecessary. I personally first went looking at the docs, then Nix source code, to see if there was any option I could override, when the VSCode settings solution is surprisingly simple.
(I personally simply wanted to change the` wordHighlightBackground` and `hoverHighlightBackground` colors, since they are the same color as the normal text selection color and thus I could not see which part of the word I have selected).
@Flameopathic 
@danth
=> doc: Add VSCode color customization tip

doc/src/development_environment.md, doc/src/modules.md
While reviewing #1493 I noticed some issues that weren't in scope for that PR.
This also highlights some redundancy/duplication between the dev-env docs and adding-modules docs. We should probably include a more general `CONTRIBUTING.md` in the docs site and move less specific guidance there, _at some point_.
@panchoh
=> doc: update docs on building docs

stylix/mk-target.nix
```
Fixes: 744385eedf23 ("mkTarget: allow _${arg}")
```
This change is a no-op because `lib.removePrefix` already performs the `lib.hasPrefix` check, except that it caches `stringLength prefix`:
- > ```nix
>   hasPrefix =
>     pref: str:
>     # Before 23.05, paths would be copied to the store before converting them
>     # to strings and comparing. This was surprising and confusing.
>     warnIf (isPath pref)
>       ''
>         lib.strings.hasPrefix: The first argument (${toString pref}) is a path value, but only strings are supported.
>             There is almost certainly a bug in the calling code, since this function always returns `false` in such a case.
>             This function also copies the path to the Nix store, which may not be what you want.
>             This behavior …
```
=> stylix: simplify mkTarget's argument trimming

.github/PULL_REQUEST_TEMPLATE.md
The “Tested locally” entry now has a pointer to the relevant section in the documentation.
(This one almost [fell through the cracks](https://github.com/nix-community/stylix/pull/1261#issuecomment-2881689203); sorry for the delay, @awwpotato!)
This is an interim fix until we tackle having a comprehensive `CONTRIBUTING.md`, as suggested by @MattSturgeon on #1499.
@awwpotato @danth
=> doc: add link to `PULL_REQUEST_TEMPLATE.md`

modules/bemenu/hm.nix
https://github.com/nix-community/stylix/pull/1368#discussion_r2148905012
cc @MattSturgeon
=> bemenu: add defaultText to fontSize

modules/hyprland/hm.nix, modules/swaylock/hm.nix, stylix/target.nix
https://github.com/nix-community/stylix/pull/1513#discussion_r2152766280
cc @MattSturgeon
=> treewide: use config in literalExpressions

modules/discord/common/color-theme.nix, modules/discord/common/font-theme.nix, modules/discord/common/theme-elements.nix, modules/discord/common/theme-header.nix, modules/discord/hm.nix, modules/discord/nixcord.nix, modules/discord/vencord.nix, modules/discord/vesktop.nix
- `template.nix` split into three files under `common`
- Some (technically out of scope) whitespace changes in `common/color-theme.nix`
- Individual files made for each target
- `common/theme-elements.nix` stores the three elements which assemble the full theme file
@Flameopathic
=> discord: use mkTarget

modules/discord/common/color-theme.nix, modules/discord/common/font-theme.nix, modules/discord/common/theme-elements.nix, modules/discord/common/theme-header.nix, modules/discord/hm.nix, modules/discord/nixcord.nix, modules/discord/vencord.nix, modules/discord/vesktop.nix
backport of https://github.com/nix-community/stylix/pull/1511 and https://github.com/nix-community/stylix/pull/1527. Should be rebased.
=> [release-25.05] discord: use mkTarget

doc/default.nix, doc/eval_compat.nix, doc/hm_compat.nix, flake/packages.nix, stylix/fonts.nix, stylix/target.nix
We don't actually need fully blown NixOS or home-manager configurations just to read the declared `options`.
Instead, we can directly call `lib.evalModules` to build a minimal configuration containing only stylix modules.
This is faster, simpler, more compartmentalised, etc.
This should allow for removing the option declaration location based filtering. Draft PR: https://github.com/danth/stylix/pull/1215.
This may also make adding nix-darwin docs easier, in the future.
Using a stubbed instance of `pkgs` while evaling the modules for the docs ensures no options accidentally use real packages in their description/default/example text.
This highlighted an issue that was resolved in https://github.com/danth/stylix/pull/1225.
With a few exceptions for `lib.stylix` functions. These are needed …
=> doc: use stricter, more minimal module evals

doc/default.nix
Follow up to #1212, originally discussed in https://github.com/danth/stylix/pull/1205#discussion_r2071539928.
The bulk of the diff is caused by a change of indentation, viewing the diff with [whitespace ignored](https://github.com/nix-community/stylix/pull/1215/files?w=1) is recommended.
Now #1212 is merged, we no longer need the option declaration location filtering, since all options present in the configuration will come from stylix modules.
One exception is the module system's builtin options, which all live in `_module`. We can simply `removeAttrs ["_module"]` before using `optionAttrSetToDocList` to remove those, though.
Additionally, I've slightly simplified the hidden-option filtering, by moving it to immediately after `optionAttrSetToDocList`.
There is still one assertion that …
=> doc: remove redundant option-location filtering

stylix/testbed/autoload.nix, stylix/testbed/default.nix
Evaluated the set of testbed modules in a separate file from where we create the testbed NixOS systems.
The first file (`autoload.nix`) has no dependency on any of Stylix's flake inputs. The second file (`default.nix`) takes the autoloaded matrix as a parameter, then imports each module into a NixOS system (and test script wrapper).
This will enable a partitioned flake to evaluate the set of testbeds without needing to fully convert them into NixOS systems with dependencies on dev-inputs. See #1289.
- Checked `nix flake show` still produces sane output
- Spot tested some testbeds still build & run
@awwpotato @trueNAHO @Flameopathic
=> stylix: extract testbed modules to `autoload.nix`

flake/packages.nix
```
Fixes: c765b15fc394 ("stylix: move testbed to a dedicated directory")
```
=> flake: infer default.nix import path

modules/rofi/hm.nix
=> rofi: use mkTarget

.github/workflows/update-flake.yml
Follow up to https://github.com/nix-community/stylix/pull/1289#discussion_r2148894496, get the app's slug and user-id and use them to construct its "name" and "email".
This matches the implementation in home-manager and nixvim:
- https://github.com/nix-community/nixvim/blob/95957f306bf6d8e40f62fd0062cf326436bf011d/.github/workflows/update.yml#L53-L67
- https://github.com/nix-community/home-manager/blob/66523b0efe93ce5b0ba96dcddcda15d36673c1f0/.github/workflows/update-flake.yml#L19-L31
I won't be offended if you reject this PR; perhaps you prefer your updates committed by github-actions[bot]? But I felt it best to open a separate PR so we don't end up having this debate on the unrelated PR (https://github.com/nix-community/stylix/pull/1289#discussion_r2148894496).
=> ci: commit as stylix-automation in updates

modules/zed/meta.nix
Fix the homepage URL of zed, which currently points to ZED the data model.
=> zed: fix homepage URL

flake.lock, modules/ashell/hm.nix, modules/ashell/meta.nix
This adds a target for ashell, a rust-based wayland status bar.
=> ashell: add target

modules/nixos-icons/overlay.nix
Fixed a problem where the `nix-snowflake.svg` would contain invalid hex colors
Closes: #1581
=> nixos-icons: pad hex color values with leading zeros

modules/fuzzel/hm.nix
Applies the iconTheme to fuzzel, if one is set.
Fuzzel otherwise always defaults to `hicolor`.
=> fuzzel: apply iconTheme

modules/rofi/hm.nix
```
… while evaluating the option `home-manager.users.azalea.programs.rofi.theme.*.active-text.value':
… while evaluating definitions from `/nix/store/y0v88m35c78ih1mbkrcdnlnfmb4pbgw6-source/modules/rofi/hm.nix':
(stack trace truncated; use '--show-trace' to show the full, detailed trace)
error: stylix: unguareded `config.lib.stylix.colors` accessed while using mkTarget
```
```
Fixes: dea0337e0b ("stylix: restrict access to config while using mkTarget (#1368)")
Fixes: 713f8dae31 ("rofi: use mkTarget (#1550)")
```
=> rofi: fix mkTarget usage

stylix/autoload.nix
```
Fixes: dea0337e0bff ("stylix: restrict access to config while using mkTarget (#1368)")
```
=> stylix: fix 'unguarded' typo

modules/i3/hm.nix, modules/i3/meta.nix, modules/sway/hm.nix, modules/sway/meta.nix
Related: #1469
Possibly related: #415
@mightyiam @butzist @trueNAHO
=> {i3,sway}: export bar configuration through options

.github/workflows/update-flake.yml
got missed in https://github.com/nix-community/stylix/pull/1289
=> ci: public flake instead of root flake

modules/wayfire/hm.nix
It appears that while migrating to `mkTarget` some of the options to wayfire itself have become mixed up into the wf-shell ones.
~While at it, I've implemented #1658, because I feel like that would have been a merge conflict.~
~Superceeds/Closes~ Might conflict with #1658
=> wayfire: mixup between wayfire and wf-shell settings

flake/dev/flake.lock, modules/wayfire/hm.nix
*This PR should not be merged untested.*
@0x5a4
=> wayfire: remove optional toString

modules/gtksourceview/overlay.nix
The overlay would reduce the gnome2 attribute set to contain just
gtksourceview. This preserves the old entries of gnome2 and only
overrides gtksourceview.
The problem was introduced in #958
@brckd
=> gtksourceview: don't overlay all of gnome2

stylix/target.nix
```
Fixes: 0449dae6d4b3 ("stylix: allow specifying `autoEnableExpr` in `mkEnableTargetWith`")
```
=> stylix: add missing trailing period in mkEnableTargetWith's description

modules/swaylock/hm.nix, modules/wpaperd/hm.nix, stylix/palette.nix
```
Remove redundant stylix.image Nix store copies, following the
improvements from commit 838df8b8ad7d ("stylix: improve `stylix.image`
type (#1414)").
```
=> treewide: remove redundant stylix.image Nix store copies

flake/deprecation/default.nix, modules/i3/hm.nix, modules/sway/hm.nix
Closes #1669
`lib.warn` can be used across nix and lix, allowing stylix to maintain a larger userbase.
=> stylix: use lib.warn instead of builtins.warn

flake/dev/pre-commit.nix, modules/waybar/hm.nix, stylix/mk-target.nix
originally proposed in https://github.com/nix-community/stylix/pull/1340#discussion_r2198135569
cc @trueNAHO @Flameopathic @danth @MattSturgeon 
reverts #1473
=> stylix: don't check lambda pattern names with deadnix

modules/zellij/hm.nix
The current Stylix module for zellij seems to be outdated, so I updated it to match the current options. The theming is based on Zellij's built-in catppuccin-mocha theme, which I then replaced with Stylix's base color variables.
Copied Zellij's built-in `catppuccin-mocha` theme, transcribed the KDL to Nix, then replaced all colors with their respective Stylix variable counterparts. This should keep styling mostly consistent across different themes, which I tested with `ayu-dark` and `grayscale-dark` myself.
Listed Nix module maintainers: @trueNAHO
=> zellij: Updated module to reflect new theme config

doc/src/testbeds.md, modules/bspwm/testbeds/bspwm.nix, modules/gnome/testbeds/gnome.nix, modules/hyprland/testbeds/hyprland.nix, modules/kde/testbeds/kde.nix, modules/mako/testbeds/mako.nix, stylix/testbed/available-graphical-environments.nix, stylix/testbed/default.nix, stylix/testbed/graphical-environments/bspwm.nix, stylix/testbed/graphical-environments/gnome.nix, stylix/testbed/graphical-environments/hyprland.nix, stylix/testbed/graphical-environments/kde.nix, stylix/testbed/modules/application.nix
This adds `stylix.testbed.ui.desktop` which allows the testbed to pick what desktop environment/window manager will be ran inside the VM.
This PR is currently a PoC and I'm open to any suggestions. I'm actively working on it, so everything is subject to change.
Relevant: https://github.com/danth/stylix/pull/1192#discussion_r2069722780
@danth @trueNAHO @awwpotato @Flameopathic 
Who else?
=> stylix: allow choosing testbed desktop

stylix/testbed/graphical-environments/gnome.nix
```
Fixes: 8c854fe383 ("stylix: allow choosing testbed desktop (#1222)")
```
was originally done in https://github.com/nix-community/stylix/pull/1429
=> stylix/testbed: respect xserver rename for gnome

stylix/testbed/default.nix
```
Conditionally load external modules in testbeds to preserve testbed
integrity by preventing unrelated code from running and potentially
invalidating its meaning.
Any performance benefit is merely a side effect of this more targeted
module loading.
```
Here is a friendly reminder to include the original commit message in the merged commit:
> remember to include the original commit message (or a reworded version) in the final squash commit message when appropriate. For example, this seems to have been missed in this PR and https://github.com/nix-community/stylix/pull/1659.
>
> -- https://github.com/nix-community/stylix/pull/1673#issuecomment-3070372774
- The following testbeds evaluate:
```console
nix build .#testbed:{alacritty,nixvim,nvf,spicetify}:dark
```
@Flameopathic @awwpotato
=> stylix: conditionally load external modules in testbeds

.github/workflows/update-flake.yml, doc/src/modules.md, flake/dev/all-maintainers.nix, flake/dev/default.nix, flake/dev/pre-commit.nix, flake/propagated-packages.nix, generated/all-maintainers.nix
required for https://github.com/nix-community/stylix/pull/1053, similar to what home-manager and nixvim have done except we don't need a python script or anything because of our project's structure.
cc @MattSturgeon @trueNAHO @danth
=> stylix: add generated all-maintainers file

.github/workflows/update-flake.yml
```
Fixes: f826d3214b ("stylix: add generated all-maintainers file (#1654)")
```
=> ci: fix generated all-maintainers path

stylix/icons.nix
```
Fixes: 1021b7d7322c ("stylix: simplify API by renaming stylix.iconTheme option to stylix.icons")
```
CC: @awwpotato, @khaneliman
=> stylix: apply stylix.iconTheme option rename to all sub-options

.github/workflows/check.yml, modules/bat/testbeds/bat.nix, modules/emacs/testbeds/emacs.nix, modules/gedit/testbeds/gedit.nix, modules/gnome-text-editor/testbeds/gnome-text-editor.nix, modules/micro/testbeds/micro.nix, modules/neovim/testbeds/neovide.nix, modules/neovim/testbeds/neovim.nix, modules/neovim/testbeds/nixvim.nix, modules/neovim/testbeds/nvf.nix, modules/neovim/testbeds/vim.nix, modules/vscode/testbeds/vscode.nix, modules/zed/testbeds/zed.nix, stylix/testbed/default.nix, stylix/testbed/modules/flake-parts.nix
```
commit e334b3019e72212289729c753873ad2a897370ca
Date:   2025-07-21 19:36:53 +0200
ci: check: add wimpysworld/nothing-but-nix Action for larger Nix store
Co-authored-by: awwpotato <awwpotato@voidq.com>
.github/workflows/check.yml | 11 +++++++++++
1 file changed, 11 insertions(+)
commit 1adb93fcbcfb1ffeef23cdf0ab4f7d17e7af0a6e
Date:   2025-07-08 19:38:21 +0200
flake: add Flake Parts tree into testbed environment
Add the Flake Parts tree into the testbed environment, enabling
realistic testing interactions.
Flake Parts is chosen over Stylix to reduce cache invalidations, and
over other flake inputs as the smallest tree.
stylix/testbed/default.nix             | 1 + …
```
=> flake: add Flake Parts tree into testbed environment

modules/mako/testbeds/mako.nix, stylix/testbed/modules/application.nix
we have a few notification daemons which I'd like to add testbeds for and repeating this a bunch seems silly.
@make-42 @trueNAHO
=> stylix/testbed: add sendNotifications option

.github/labeler.yml
manual backport of https://github.com/nix-community/stylix/pull/1755
`ci: consistently format singleton list` isn't being backported because it doesn't apply to the stable branch.
=> [release-25.05] ci: add more top-level labels to provide better overview

doc/src/commit_convention.md
This PR is a superset of https://github.com/nix-community/stylix/pull/1622.
This PR is best viewed in rendered form:
```console
nix run github:trueNAHO/stylix/doc-commit-convention-overhaul-and-formalize-unspoken-rules#doc
```
---
CC: @awwpotato @danth
- *Follows the proposed commit convention.*
=> doc: commit_convention: overhaul and formalize unspoken rules

.github/workflows/check.yml, .github/workflows/doc.yml
already discussed with danth on matrix, allows for a bigger cache and reduces the number of things that need to be managed by stylix maintainers.
> [!NOTE]
> `CACHIX_AUTH_TOKEN` must be deleted from [action secrets settings](https://github.com/nix-community/stylix/settings/secrets/actions) when this pr is merged so we will inherit nix-community's auth token.
=> ci: use nix-community cachix

doc/src/modules.md
```
Fixes: f826d3214b8a ("stylix: add generated all-maintainers file (#1654)")
```
---
=> doc/src/modules: fix admonition formatting

modules/anki/meta.nix
```
Fixes: 1b5e1c5642cf ("anki: init (#1801)")
```
Capitalization based on:
https://github.com/nix-community/stylix/blob/1b5e1c5642cf96e07daf14ae4c5ddd23d7ed5623/modules/anki/hm.nix#L10
---
@lomenzel
=> anki/meta: fix name capitalization

stylix/droid/default.nix, stylix/droid/fonts.nix, stylix/droid/palette.nix
Fixed the lack of import of specific settings files for the `nix-on-droid` module,
and removed a duplicate and broken import of the universal styles configuration.
This made it possible to export color palette files and set fonts for this system.
---
=> stylix/droid: fix import droid modules

modules/gnome/hm.nix
Just a small change to get the UUID from a single source of truth, rather than hardcoding it. The generated script is exactly the same as before.
---
=> gnome: get extension UUID from package metadata

.github/workflows/request-reviewers.yml
```
Closes: https://github.com/nix-community/stylix/issues/1867
```
I suggest optimistically closing https://github.com/nix-community/stylix/issues/1867 with this PR. We can re-open it, if the issue is still not resolved.
This PR_AUTHOR filtering was accidentally removed in the following patch:
> ```patch
> From c81f587ce7a796b4bbfb7792ae42b12e1446fb29 Mon Sep 17 00:00:00 2001
> From: NAHO <90870942+trueNAHO@users.noreply.github.com>
> Date: Thu, 24 Jul 2025 20:24:55 +0200
> Subject: [PATCH 3/5] ci: ping-maintainers: overhaul implementation
>
> ---
>  .github/workflows/ping-maintainers.yml | 79 +++++++++++++-------------
>  1 file changed, 39 insertions(+), 40 deletions(-)
>
> diff --git a/.github/workflows/ping-maintainers.yml b/.github/workflows/ping-maintainers.yml
> index …
```
=> ci: request-reviewers: do not request PR author

stylix/testbed/default.nix
```
Fixes: c32c82e460b9 ("zen-browser: init (#1694)")
```
Motivated by https://github.com/nix-community/stylix/pull/1902#discussion_r2374763408.
---
=> stylix/testbed/default: simplify attribute set declaration

doc/default.nix, stylix/autoload.nix, stylix/testbed/modules/common.nix
```
Remove optional builtins prefixes from prelude functions by running:
builtins=(
abort
baseNameOf
break
derivation
derivationStrict
dirOf
false
fetchGit
fetchMercurial
fetchTarball
fetchTree
fromTOML
import
isNull
map
null
placeholder
removeAttrs
scopedImport
throw
toString
true
)
fd --type file --exec-batch sed --in-place --regexp-extended "
s/\<builtins\.($(
printf '%s\n' "${builtins[@]}" |
paste --delimiter '|' --serial -
))\>/\1/g
"
nix fmt
This patch is heavily inspired by [1] ("treewide: remove optional
builtins prefixes from prelude functions").
[1]: https://github.com/NixOS/nixpkgs/pull/444432
```
---
- Since similar patches have not been backported, this is manually backported in https://github.com/nix-community/stylix/pull/1914.
=> treewide: remove optional builtins prefixes from prelude functions

doc/default.nix, flake/deprecation/per-system-option.nix, modules/bemenu/hm.nix, modules/glance/testbeds/glance-hm.nix, modules/glance/testbeds/glance-nixos.nix, modules/neovim/neovim.nix, modules/rofi/hm.nix, modules/swaync/hm.nix, modules/waybar/hm.nix, modules/wezterm/hm.nix, modules/zathura/hm.nix, stylix/autoload.nix, stylix/testbed/modules/common.nix
```
treewide: remove optional builtins prefixes from prelude functions
Remove optional builtins prefixes from prelude functions by running:
builtins=(
abort
baseNameOf
break
derivation
derivationStrict
dirOf
false
fetchGit
fetchMercurial
fetchTarball
fetchTree
fromTOML
import
isNull
map
null
placeholder
removeAttrs
scopedImport
throw
toString
true
)
fd --type file --exec-batch sed --in-place --regexp-extended "
s/\<builtins\.($(
printf '%s\n' "${builtins[@]}" |
paste --delimiter '|' --serial -
))\>/\1/g
"
nix fmt
This patch is heavily inspired by [1] ("treewide: remove optional
builtins prefixes from prelude functions").
[1]: https://github.com/NixOS/nixpkgs/pull/444432
```
---
- This is the manual backport of https://github.com/nix-community/stylix/pull/1915.
=> [release-25.05] treewide: remove optional builtins prefixes from prelude functions

modules/discord/nixcord.nix, modules/zen-browser/hm.nix
```
Fixes: c32c82e460b9 ("zen-browser: init (#1694)")
Fixes: e594886eb095 ("nixcord: init (#767)")
```
For convenience, here is the `--ignore-all-space` diff:
```patch
commit 0c67dd9ee600b961256e34e091e0a09d7804f6e7
Date:   2025-09-27 18:56:28 +0200
modules: replace static builtins.hasAttrs instances with '?' operator
Fixes: c32c82e460b9 ("zen-browser: init (#1694)")
Fixes: e594886eb095 ("nixcord: init (#767)")
diff --git a/modules/discord/nixcord.nix b/modules/discord/nixcord.nix
index b7409bce..3aeb621c 100644
--- a/modules/discord/nixcord.nix
+++ b/modules/discord/nixcord.nix
@@ -32,7 +32,7 @@ mkTarget {
lib.mkIf
(cfg.themeBody != (import ./common/theme-header.nix) || cfg.extraCss != "")
(
-          lib.optionalAttrs …
```
=> modules: replace static builtins.hasAttrs instances with '?' operator

.github/workflows/check.yml
```
commit cbb9010d16a265c4b67495fa60d7067b87fc7389
Date:   2025-10-02 19:06:22 +0200
ci: check: bump x86_64-darwin runner to macos-15
.github/workflows/check.yml | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
commit 22d291b0a5f7570807337b4d9bff8a5d17536d30
Date:   2025-10-02 19:07:06 +0200
ci: check: use correct x86_64-darwin runner
.github/workflows/check.yml | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
```
> The macOS 13 runner image will be retired by December 4th, 2025.
>
> [...]
>
> For users that require the x86_64 (Intel) architecture, jobs can be migrated to one of the following labels:
>
> * macos-15-intel (new)
> * macos-14-large
> * …
=> ci: check: bump and use correct x86_64-darwin runner

modules/hyprpanel/hm.nix
```
Fixes: 3f70c5855572 ("hyprpanel: init (#1916)")
```
CC: @khas-amir
---
- Commit 3f70c5855572 has not been backported yet.
=> hyprpanel: more granularly split configElements
